#ifndef EXAMPLE_TYPES_H
#define EXAMPLE_TYPES_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/temperature.h"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/set_point.h"
#include <rosidl_runtime_c/string_functions.h>

static inline temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Temperature example_Temperature(void);
static inline temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__SetPoint example_SetPoint(void);

static inline temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Temperature example_Temperature(void) {
    temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Temperature msg = {0};
    msg.degrees.data = 0.0f;
    msg.unit.temp_unit = temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__TempUnit__TEMP_UNIT_FAHRENHEIT;
    return msg;
}

static inline temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__SetPoint example_SetPoint(void) {
    temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__SetPoint msg = {0};
    msg.low = example_Temperature();
    msg.high = example_Temperature();
    return msg;
}

#endif  // EXAMPLE_TYPES_H
