#ifndef EXAMPLE_TYPES_HPP
#define EXAMPLE_TYPES_HPP

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include "turtle_control_naming_cpp_pkg_interfaces/msg/wheel_speed.hpp"
#include "turtle_control_naming_cpp_pkg_interfaces/msg/trim_command.hpp"

static inline turtle_control_naming_cpp_pkg_interfaces::msg::WheelSpeed example_WheelSpeed();
static inline turtle_control_naming_cpp_pkg_interfaces::msg::TrimCommand example_TrimCommand();

static inline turtle_control_naming_cpp_pkg_interfaces::msg::WheelSpeed example_WheelSpeed() {
    turtle_control_naming_cpp_pkg_interfaces::msg::WheelSpeed msg;
    msg.rpm.data = 0.0f;
    return msg;
}

static inline turtle_control_naming_cpp_pkg_interfaces::msg::TrimCommand example_TrimCommand() {
    turtle_control_naming_cpp_pkg_interfaces::msg::TrimCommand msg;
    msg.delta_rpm.data = 0.0f;
    return msg;
}

#endif  // EXAMPLE_TYPES_HPP
