#include "turtle_control_naming_microros_pkg/base_headers/enum_converter.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

const char* enumToString_OperatingMode(uint8_t value)
{
    switch (value) {
        case turtle_control_naming_cpp_pkg_interfaces__msg__OperatingMode__OPERATING_MODE_IDLE: return "Idle";
        case turtle_control_naming_cpp_pkg_interfaces__msg__OperatingMode__OPERATING_MODE_RUN: return "Run";
        case turtle_control_naming_cpp_pkg_interfaces__msg__OperatingMode__OPERATING_MODE_FAULT: return "Fault";
        default: return "Unknown";
    }
}

