#ifndef TCP_TEMPSENSOR_BASE_H
#define TCP_TEMPSENSOR_BASE_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <stdio.h>
#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/temperature.h"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/empty.h"
#include "temp_control_mixed_u_ros_microros_pkg/base_headers/enum_converter.h"
#include "temp_control_mixed_u_ros_microros_pkg/base_headers/example_types.h"

#define PRINT_INFO(fmt, ...) printf("[INFO] [tcp_tempSensor] " fmt "\n", ##__VA_ARGS__)
#define PRINT_WARN(fmt, ...) printf("[WARN] [tcp_tempSensor] " fmt "\n", ##__VA_ARGS__)
#define PRINT_ERROR(fmt, ...) printf("[ERROR] [tcp_tempSensor] " fmt "\n", ##__VA_ARGS__)

static inline const char* _MESSAGE_TO_STRING_Temperature(
        const temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Temperature* msg, char* _buf, int _buf_size) {
    snprintf(_buf, _buf_size, "Temperature{degrees: %f, unit: %s}",
          msg->degrees.data,
                  enumToString_TempUnit(msg->unit.temp_unit));
    return _buf;
}

static char _MESSAGE_TO_STRING_buf[512];
#define MESSAGE_TO_STRING(msg) _Generic((msg), \
    temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Temperature*: _MESSAGE_TO_STRING_Temperature((msg), _MESSAGE_TO_STRING_buf, sizeof(_MESSAGE_TO_STRING_buf)), \
    default: "(unknown type)")


//=================================================
//  N o d e   S t a t e
//=================================================

typedef struct {
    rcl_node_t node;
    rclc_support_t support;
    rcl_allocator_t allocator;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rcl_publisher_t tcp_tempSensor_currentTemp_publisher_1;
    rcl_publisher_t tcp_tempSensor_currentTemp_publisher_2;
    rcl_publisher_t tcp_tempSensor_tempChanged_publisher;

    //=================================================
    //  C a l l b a c k   a n d   T i m e r
    //=================================================
    rcl_timer_t period_timer;
    rclc_executor_t executor;
} tcp_tempSensor_base_t;

void tcp_tempSensor_base_init(tcp_tempSensor_base_t * self);
void tcp_tempSensor_base_spin(tcp_tempSensor_base_t * self);

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void put_currentTemp(tcp_tempSensor_base_t * self, temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Temperature * msg);
void put_tempChanged(tcp_tempSensor_base_t * self);

#endif  // TCP_TEMPSENSOR_BASE_H
