#include "rclcpp/rclcpp.hpp"
#include "rcl_interfaces/msg/log.hpp"
#include <queue>
#include <sstream>

#include "uros_demo_gumbo_cpp_pkg/base_headers/example_types.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

class proc_logger_base : public rclcpp::Node
{
protected:
    proc_logger_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================


    #define PRINT_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define PRINT_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define PRINT_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)


private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;


    //=================================================
    //  C o m p u t e    E n t r y    P o i n t
    //=================================================
    virtual void handle_rosout(const rcl_interfaces::msg::Log::SharedPtr msg) = 0;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<rcl_interfaces::msg::Log>::SharedPtr proc_logger_rosout_subscription_;


};
