#ifndef ENUM_CONVERTER_H
#define ENUM_CONVERTER_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <stdint.h>
#include "turtle_control_naming_cpp_pkg_interfaces/msg/operating_mode.h"

// C does not support function overloading; enum types are encoded in the name
const char* enumToString_OperatingMode(uint8_t value);

#endif  // ENUM_CONVERTER_H
