#ifndef PROC_ENCODER_BASE_H
#define PROC_ENCODER_BASE_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <stdio.h>
                  #include <stdbool.h>
#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <rcutils/logging_macros.h>
#include "turtle_control_naming_cpp_pkg_interfaces/msg/operating_mode.h"
#include "turtle_control_naming_cpp_pkg_interfaces/msg/wheel_speed.h"
#include "turtle_control_naming_cpp_pkg_interfaces/msg/empty.h"
#include "turtle_control_naming_cpp_pkg_interfaces/msg/trim_command.h"
#include "turtle_control_naming_microros_pkg/base_headers/enum_converter.h"
#include "turtle_control_naming_microros_pkg/base_headers/example_types.h"

// Logger name used by the PRINT_* macros.  It defaults to the node name and is
// updated to the node's actual logger name (rcl_node_get_logger_name) during
// proc_encoder_base_init.
extern const char * proc_encoder_logger_name;

#define PRINT_INFO(fmt, ...) RCUTILS_LOG_INFO_NAMED(proc_encoder_logger_name, fmt, ##__VA_ARGS__)
#define PRINT_WARN(fmt, ...) RCUTILS_LOG_WARN_NAMED(proc_encoder_logger_name, fmt, ##__VA_ARGS__)
#define PRINT_ERROR(fmt, ...) RCUTILS_LOG_ERROR_NAMED(proc_encoder_logger_name, fmt, ##__VA_ARGS__)

// rcl/rclc report entity-creation failures by return code rather than by trapping,
// and on an MCU the usual causes -- an exhausted RMW_UXRCE_MAX_* pool, an
// unreachable agent -- are exactly the ones worth seeing.  Running on past one
// leaves a node that spins normally but silently never publishes or receives, so
// proc_encoder_base_init stops at the first failure and hands the status back.
// Expands to a return, so it is usable only in a function returning rcl_ret_t.
#define RCL_CHECK(fn) do { rcl_ret_t rc_ = (fn); if (rc_ != RCL_RET_OK) { PRINT_ERROR("rcl call failed at %s:%d with status %d", __FILE__, __LINE__, (int) rc_); return rc_; } } while (0)

static inline const char* _MESSAGE_TO_STRING_WheelSpeed(
        const turtle_control_naming_cpp_pkg_interfaces__msg__WheelSpeed* msg, char* _buf, int _buf_size) {
    snprintf(_buf, _buf_size, "WheelSpeed{rpm: %f}",
          msg->rpm.data);
    return _buf;
}

static char _MESSAGE_TO_STRING_buf[512];
#define MESSAGE_TO_STRING(msg) _Generic((msg), \
    turtle_control_naming_cpp_pkg_interfaces__msg__WheelSpeed*: _MESSAGE_TO_STRING_WheelSpeed((msg), _MESSAGE_TO_STRING_buf, sizeof(_MESSAGE_TO_STRING_buf)), \
    default: "(unknown type)")


//=================================================
//  N o d e   S t a t e
//=================================================

typedef struct {
    rcl_node_t node;
    rclc_support_t support;
    rcl_allocator_t allocator;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rcl_publisher_t proc_encoder_speed_publisher;
    rcl_publisher_t proc_encoder_overspeed_publisher;

    //=================================================
    //  S u b s c r i p t i o n s
    //=================================================
    rcl_subscription_t proc_encoder_mode_subscription;
    turtle_control_naming_cpp_pkg_interfaces__msg__OperatingMode proc_encoder_mode_msg;
    rcl_subscription_t proc_encoder_calibrate_subscription;
    turtle_control_naming_cpp_pkg_interfaces__msg__Empty proc_encoder_calibrate_msg;
    rcl_subscription_t proc_encoder_trim_subscription;
    turtle_control_naming_cpp_pkg_interfaces__msg__TrimCommand proc_encoder_trim_msg;

    // Arrivals wait here for the next dispatch -- see proc_encoder_receiveInputs
    // calibrate: event port, so only the pending count is queued (Queue_Size 2)
    size_t proc_encoder_calibrate_count;
    bool proc_encoder_calibrate_hasEvent;
    // trim: Queue_Size 4 ring buffer, plus the entry frozen for this dispatch
    turtle_control_naming_cpp_pkg_interfaces__msg__TrimCommand proc_encoder_trim_queue[4];
    size_t proc_encoder_trim_head;
    size_t proc_encoder_trim_count;
    turtle_control_naming_cpp_pkg_interfaces__msg__TrimCommand proc_encoder_trim_frozen;
    bool proc_encoder_trim_hasEvent;

    //=================================================
    //  C a l l b a c k   a n d   T i m e r
    //=================================================
    rcl_timer_t period_timer;
    rclc_executor_t executor;
} proc_encoder_base_t;

// Returns RCL_RET_OK, or the status of the first rcl/rclc call that failed.
rcl_ret_t proc_encoder_base_init(proc_encoder_base_t * self);
void proc_encoder_base_spin(proc_encoder_base_t * self);

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void put_speed(proc_encoder_base_t * self, turtle_control_naming_cpp_pkg_interfaces__msg__WheelSpeed * msg);
void put_overspeed(proc_encoder_base_t * self);

//=================================================
//  D a t a   P o r t   A c c e s s
//=================================================

turtle_control_naming_cpp_pkg_interfaces__msg__OperatingMode * get_mode(proc_encoder_base_t * self);

//=================================================
//  Q u e u e d   P o r t   A c c e s s
//=================================================

// true when an event was dequeued for this dispatch
bool has_calibrate(proc_encoder_base_t * self);
// the message dequeued for this dispatch, or NULL if none arrived
turtle_control_naming_cpp_pkg_interfaces__msg__TrimCommand * get_trim(proc_encoder_base_t * self);

#endif  // PROC_ENCODER_BASE_H
