// #Sireum

package tc.GUMBO_Definitions

import org.sireum._
import tc._

// this file is autogenerated, do not edit

object GUMBO__Library {
  @strictpure def inRange(temp: TempSensor.Temperature_i): Base_Types.Boolean = temp.degrees >= -50.0f &&
    temp.degrees <= 150.0f &&
    temp.degrees >= TempSensor.GUMBO__Library.gminTempDegrees() &&
    temp.degrees <= TempSensor.GUMBO__Library.gmaxTempDegrees()

  @strictpure def toFahrenheit(temp: TempSensor.Temperature_i): TempSensor.Temperature_i = TempSensor.Temperature_i(temp.degrees)
}
