#ifndef EXAMPLE_TYPES_H
#define EXAMPLE_TYPES_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include "turtle_control_structure_cpp_pkg_interfaces/msg/trim_command.h"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/wheel_speed.h"
#include <rosidl_runtime_c/string_functions.h>

static inline turtle_control_structure_cpp_pkg_interfaces__msg__TrimCommand example_TrimCommand(void);
static inline turtle_control_structure_cpp_pkg_interfaces__msg__WheelSpeed example_WheelSpeed(void);

static inline turtle_control_structure_cpp_pkg_interfaces__msg__TrimCommand example_TrimCommand(void) {
    turtle_control_structure_cpp_pkg_interfaces__msg__TrimCommand msg = {0};
    msg.delta_rpm.data = 0.0f;
    return msg;
}

static inline turtle_control_structure_cpp_pkg_interfaces__msg__WheelSpeed example_WheelSpeed(void) {
    turtle_control_structure_cpp_pkg_interfaces__msg__WheelSpeed msg = {0};
    msg.rpm.data = 0.0f;
    return msg;
}

#endif  // EXAMPLE_TYPES_H
