#ifndef PROC_ENCODER_BASE_H
#define PROC_ENCODER_BASE_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <stdio.h>
#include <stdbool.h>
#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <rcutils/logging_macros.h>
#include "turtle_control_structure_cpp_pkg_interfaces/msg/operating_mode.h"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/trim_command.h"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/wheel_speed.h"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/empty.h"
#include "turtle_control_structure_microros_pkg/base_headers/enum_converter.h"
#include "turtle_control_structure_microros_pkg/base_headers/example_types.h"

// Logger name used by the LOG_* macros.  It defaults to the node name and is
// updated to the node's actual logger name (rcl_node_get_logger_name) during
// proc_encoder_base_init.
extern const char * proc_encoder_logger_name;

#define LOG_INFO(fmt, ...) RCUTILS_LOG_INFO_NAMED(proc_encoder_logger_name, fmt, ##__VA_ARGS__)
#define LOG_WARN(fmt, ...) RCUTILS_LOG_WARN_NAMED(proc_encoder_logger_name, fmt, ##__VA_ARGS__)
#define LOG_ERROR(fmt, ...) RCUTILS_LOG_ERROR_NAMED(proc_encoder_logger_name, fmt, ##__VA_ARGS__)

// rcl/rclc report entity-creation failures by return code rather than by trapping,
// and on an MCU the usual causes -- an exhausted RMW_UXRCE_MAX_* pool, an
// unreachable agent -- are exactly the ones worth seeing.  Running on past one
// leaves a node that spins normally but silently never publishes or receives, so
// proc_encoder_base_init stops at the first failure and hands the status back.
// Expands to a return, so it is usable only in a function returning rcl_ret_t.
#define RCL_CHECK(fn) do { rcl_ret_t rc_ = (fn); if (rc_ != RCL_RET_OK) { LOG_ERROR("rcl call failed at %s:%d with status %d", __FILE__, __LINE__, (int) rc_); return rc_; } } while (0)

static inline const char* _MESSAGE_TO_STRING_WheelSpeed(
        const turtle_control_structure_cpp_pkg_interfaces__msg__WheelSpeed* msg, char* _buf, int _buf_size) {
    snprintf(_buf, _buf_size, "WheelSpeed{rpm: %f}",
          msg->rpm.data);
    return _buf;
}

// Scratch buffer for the printers above, defined once in the node's base source.  It is
// declared here rather than defined so that each translation unit including this header
// shares one buffer instead of getting a copy.  Sharing is safe because the rclc executor
// is single-threaded: no two expansions of MESSAGE_TO_STRING can be live at once.
extern char _MESSAGE_TO_STRING_buf[512];
#define MESSAGE_TO_STRING(msg) _Generic((msg), \
    turtle_control_structure_cpp_pkg_interfaces__msg__WheelSpeed*: _MESSAGE_TO_STRING_WheelSpeed((msg), _MESSAGE_TO_STRING_buf, sizeof(_MESSAGE_TO_STRING_buf)), \
    default: "(unknown type)")


//=================================================
//  N o d e   S t a t e
//=================================================

typedef struct {
    rcl_node_t node;
    rclc_support_t support;
    rcl_allocator_t allocator;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rcl_publisher_t proc_encoder_speed_publisher;
    // speed: the copy is required -- put_speed is handed a pointer to a
    // local in the entry point, and sendOutputs runs after that frame is gone
    turtle_control_structure_cpp_pkg_interfaces__msg__WheelSpeed proc_encoder_speed_out;
    bool proc_encoder_speed_out_hasValue;
    rcl_publisher_t proc_encoder_overspeed_publisher;
    // overspeed: an event port carries no payload, so the flag is the whole record
    bool proc_encoder_overspeed_out_hasValue;

    //=================================================
    //  S u b s c r i p t i o n s
    //=================================================
    rcl_subscription_t proc_encoder_mode_subscription;
    turtle_control_structure_cpp_pkg_interfaces__msg__OperatingMode proc_encoder_mode_msg;
    rcl_subscription_t proc_encoder_trim_subscription;
    turtle_control_structure_cpp_pkg_interfaces__msg__TrimCommand proc_encoder_trim_msg;

    // Arrivals wait here for the next dispatch -- see proc_encoder_receiveInputs
    // trim: only the AADL default Queue_Size of 1 is supported, so an
    // arrival needs no ring -- just the two flags below.
    // The payload stays in proc_encoder_trim_msg, which the executor
    // writes before it invokes the callback.
    bool proc_encoder_trim_pending;
    bool proc_encoder_trim_hasEvent;

    //=================================================
    //  C a l l b a c k   a n d   T i m e r
    //=================================================
    rcl_timer_t period_timer;
    rclc_executor_t executor;
} proc_encoder_base_t;

// Returns RCL_RET_OK, or the status of the first rcl/rclc call that failed.
rcl_ret_t proc_encoder_base_init(proc_encoder_base_t * self);
void proc_encoder_base_spin(proc_encoder_base_t * self);

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void put_speed(proc_encoder_base_t * self, turtle_control_structure_cpp_pkg_interfaces__msg__WheelSpeed * msg);
void put_overspeed(proc_encoder_base_t * self);

//=================================================
//  D a t a   P o r t   A c c e s s
//=================================================

turtle_control_structure_cpp_pkg_interfaces__msg__OperatingMode * get_mode(proc_encoder_base_t * self);

//=================================================
//  Q u e u e d   P o r t   A c c e s s
//=================================================

// the message dequeued for this dispatch, or NULL if none arrived
turtle_control_structure_cpp_pkg_interfaces__msg__TrimCommand * get_trim(proc_encoder_base_t * self);

#endif  // PROC_ENCODER_BASE_H
