#include "building_control_cpp_pkg/base_headers/tcp_fan_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

tcp_fan_base::tcp_fan_base() : Node("tcp_fan")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    tcp_fan_fanCmd_subscription_ = this->create_subscription<building_control_cpp_pkg_interfaces::msg::FanCmd>(
        "tcp_fan_fanCmd",
        1,
        std::bind(&tcp_fan_base::accept_fanCmd, this, std::placeholders::_1), subscription_options_);

    tcp_fan_fanAck_publisher_ = this->create_publisher<building_control_cpp_pkg_interfaces::msg::FanAck>(
        "tcp_tempControl_fanAck",
        1);

    // Used by receiveInputs
    inDataPortTupleVector = {
    };

    // Used by sendOutputs
    outPortTupleVector = {
        {&applicationOut_fanAck, &infrastructureOut_fanAck, &tcp_fan_base::sendOut_fanAck}
    };

}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void tcp_fan_base::accept_fanCmd(building_control_cpp_pkg_interfaces::msg::FanCmd msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_fanCmd, msg);
    }
    std::thread([this]() {
        // One dispatch at a time.  This is what the old single mutex_ achieved by being
        // held for the whole lambda; it is kept separate so that the state lock can be
        // released around the entry point.
        std::lock_guard<std::mutex> dispatch(dispatch_mutex_);

        MsgType dispatched;
        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            receiveInputs(infrastructureIn_fanCmd, applicationIn_fanCmd);
            if (applicationIn_fanCmd.empty()) return;
            dispatched = applicationIn_fanCmd.front();
        }

        // Deliberately outside state_mutex_: the handler is user code and calls
        // put_<port>/get_<port>, which take that lock themselves.  The value stays on
        // applicationIn_fanCmd until the handler returns, because get_fanCmd
        // reads it from there.
        handle_fanCmd_base(dispatched);

        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            if (!applicationIn_fanCmd.empty()) {
                applicationIn_fanCmd.pop();
            }
        }

        sendOutputs();
    }).detach();
}

void tcp_fan_base::handle_fanCmd_base(MsgType msg)
{
    if (auto typedMsg = std::get_if<building_control_cpp_pkg_interfaces::msg::FanCmd>(&msg)) {
        handle_fanCmd(*typedMsg);
    } else {
        LOG_ERROR("Receiving wrong type of variable on port fanCmd.\nThis shouldn't be possible.  If you are seeing this message, please notify this tool's current maintainer.");
    }
}

void tcp_fan_base::sendOut_fanAck(MsgType msg)
{
    if (auto typedMsg = std::get_if<building_control_cpp_pkg_interfaces::msg::FanAck>(&msg)) {
        tcp_fan_fanAck_publisher_->publish(*typedMsg);
    } else {
        LOG_ERROR("Sending out wrong type of variable on port fanAck.\nThis shouldn't be possible.  If you are seeing this message, please notify this tool's current maintainer.");
    }
}

void tcp_fan_base::put_fanAck(building_control_cpp_pkg_interfaces::msg::FanAck msg)
{
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(applicationOut_fanAck, msg);
}

void tcp_fan_base::receiveInputs(std::queue<MsgType>& infrastructureQueue, std::queue<MsgType>& applicationQueue) {
    if (!infrastructureQueue.empty()) {
        MsgType eventMsg = infrastructureQueue.front();
        infrastructureQueue.pop();
        enqueue(applicationQueue, eventMsg);
    }

    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inDataPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            enqueue(*std::get<1>(port), msg);
        }
    }
}

void tcp_fan_base::enqueue(std::queue<MsgType>& queue, MsgType val) {
    if (queue.size() >= 1) {
        queue.pop();
    }
    queue.push(val);
}

void tcp_fan_base::sendOutputs() {
    // The queue work happens under state_mutex_; the publishing does not.  accept_<port>
    // runs from a subscription callback, so the middleware already holds locks of its own
    // when it takes state_mutex_.  Publishing while holding state_mutex_ would establish
    // the reverse order and put this lock into a cycle with the middleware's.  No such
    // cycle has been observed -- the lock-order inversions ThreadSanitizer reports here
    // are internal to Fast DDS and involve neither of this node's mutexes -- so this is
    // ordering hygiene rather than a fix for a diagnosed deadlock.  It also keeps the
    // critical section off the wire.  Collect first, release, then publish.
    std::vector<std::pair<void (tcp_fan_base::*)(MsgType), MsgType>> pending;
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (tcp_fan_base::*)(MsgType)> port : outPortTupleVector) {
            auto applicationQueue = std::get<0>(port);
            if (applicationQueue->size() != 0) {
                auto msg = applicationQueue->front();
                applicationQueue->pop();
                enqueue(*std::get<1>(port), msg);
            }
        }

        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (tcp_fan_base::*)(MsgType)> port : outPortTupleVector) {
            auto infrastructureQueue = std::get<1>(port);
            if (infrastructureQueue->size() != 0) {
                auto msg = infrastructureQueue->front();
                infrastructureQueue->pop();
                pending.emplace_back(std::get<2>(port), msg);
            }
        }
    }

    // Still one dispatch's worth of outputs, released together -- only the lock is gone.
    for (auto& entry : pending) {
        (this->*entry.first)(entry.second);
    }
}
