// #Sireum

package prod_cons__JVM.ProdConsFlows

import org.sireum._
import prod_cons__JVM._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
object Filter_p_p_filterp_GumboX {
  /** I-Assm: Integration constraint on filterp's incoming data port a_data_in
    *
    * assume a_gt_10
    *   Value received on a will always be greater than 10
    */
  @strictpure def I_Assm_a_data_in(a_data_in: ProdConsFlows.Container_i): B =
    a_data_in.value > 10

  // I-Assm-Guard: Integration constraint on filterp's incoming data port a_data_in
  @strictpure def I_Assm_Guard_a_data_in(a_data_in: ProdConsFlows.Container_i): B =
    I_Assm_a_data_in(a_data_in)

  /** I-Guar: Integration constraint on filterp's outgoing data port e_data_out
    *
    * guarantee e_gt_6
    *   Values placed on e must always be greate than 6
    */
  @strictpure def I_Guar_e_data_out(e_data_out: ProdConsFlows.Container_i): B =
    e_data_out.value > 6

  // I_Guar-Guard: Integration constraint on filterp's outgoing data port e_data_out
  @strictpure def I_Guar_Guard_e_data_out(e_data_out: Option[ProdConsFlows.Container_i]): B =
    e_data_out.nonEmpty -->: I_Guar_e_data_out(e_data_out.get)

  /** I-Assm: Integration constraint on filterp's incoming event data port b_event_data_in
    *
    * assume b_gt_8
    *   Value received on b will always be greater than 8
    */
  @strictpure def I_Assm_b_event_data_in(b_event_data_in: ProdConsFlows.Container_i): B =
    b_event_data_in.value > 8

  // I-Assm-Guard: Integration constraint on filterp's incoming event data port b_event_data_in
  @strictpure def I_Assm_Guard_b_event_data_in(b_event_data_in: Option[ProdConsFlows.Container_i]): B =
    b_event_data_in.nonEmpty -->: I_Assm_b_event_data_in(b_event_data_in.get)

  /** I-Guar: Integration constraint on filterp's outgoing event data port f_event_data_out
    *
    * guarantee f_gt_4
    *   Values placed on f must always be greate than 4
    */
  @strictpure def I_Guar_f_event_data_out(f_event_data_out: ProdConsFlows.Container_i): B =
    f_event_data_out.value > 4

  // I_Guar-Guard: Integration constraint on filterp's outgoing event data port f_event_data_out
  @strictpure def I_Guar_Guard_f_event_data_out(f_event_data_out: Option[ProdConsFlows.Container_i]): B =
    f_event_data_out.nonEmpty -->: I_Guar_f_event_data_out(f_event_data_out.get)

  /** Initialize Entrypoint Contract
    *
    * guarantee e_data_out_initializes
    *   Must initialize outgoing data ports.
    *   Perhaps this should be a built-in emitted Logika check
    *   to match GUMBOX. e.g., GUMBOX adds post checks
    *   that ensures all outgoing data/event-data ports satisify
    *   data type invariants and/or integration constraints
    *   regardless of whether a component has contracts
    * @param api_e_data_out outgoing data port
    */
  @strictpure def initialize_e_data_out_initializes (
      api_e_data_out: ProdConsFlows.Container_i): B =
    api_e_data_out.value == 7

  /** IEP-Guar: Initialize Entrypoint Contracts for filterp
    *
    * @param api_h_event_out outgoing event port
    * @param api_f_event_data_out outgoing event data port
    * @param api_g_event_data_out outgoing event data port
    * @param api_e_data_out outgoing data port
    */
  @strictpure def initialize_IEP_Guar (
      api_h_event_out: Option[art.Empty],
      api_f_event_data_out: Option[ProdConsFlows.Container_i],
      api_g_event_data_out: Option[ProdConsFlows.Container_i],
      api_e_data_out: ProdConsFlows.Container_i): B =
    initialize_e_data_out_initializes(api_e_data_out)

  /** IEP-Post: Initialize Entrypoint Post-Condition
    *
    * @param api_h_event_out outgoing event port
    * @param api_f_event_data_out outgoing event data port
    * @param api_g_event_data_out outgoing event data port
    * @param api_e_data_out outgoing data port
    */
  @strictpure def inititialize_IEP_Post (
      api_h_event_out: Option[art.Empty],
      api_f_event_data_out: Option[ProdConsFlows.Container_i],
      api_g_event_data_out: Option[ProdConsFlows.Container_i],
      api_e_data_out: ProdConsFlows.Container_i): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with filterp's state variables and outgoing ports
     ProdConsFlows.Container_i_GumboX.D_Inv_Guard_Container_i(api_f_event_data_out) &
     ProdConsFlows.Container_i_GumboX.D_Inv_Guard_Container_i(api_g_event_data_out) &
     ProdConsFlows.Container_i_GumboX.D_Inv_Container_i(api_e_data_out) & 

     // I-Guar-Guard: Integration constraints for filterp's outgoing ports"
     I_Guar_e_data_out(api_e_data_out) &
     I_Guar_Guard_f_event_data_out(api_f_event_data_out) & 

     // IEP-Guar: Initialize Entrypoint contract for filterp
     initialize_IEP_Guar(api_h_event_out, api_f_event_data_out, api_g_event_data_out, api_e_data_out))

  /** IEP-Post: Initialize Entrypoint Post-Condition via container
    *
    * @param post Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def inititialize_IEP_Post_Container (post: Filter_p_p_filterp_PostState_Container_PS): B =
    inititialize_IEP_Post (
      api_h_event_out = post.api_h_event_out,
      api_f_event_data_out = post.api_f_event_data_out,
      api_g_event_data_out = post.api_g_event_data_out,
      api_e_data_out = post.api_e_data_out)

  /** CEP-Pre: Compute Entrypoint Pre-Condition for filterp
    *
    * @param api_d_event_in incoming event port
    * @param api_b_event_data_in incoming event data port
    * @param api_c_event_data_in incoming event data port
    * @param api_a_data_in incoming data port
    */
  @strictpure def compute_CEP_Pre (
      api_d_event_in: Option[art.Empty],
      api_b_event_data_in: Option[ProdConsFlows.Container_i],
      api_c_event_data_in: Option[ProdConsFlows.Container_i],
      api_a_data_in: ProdConsFlows.Container_i): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with filterp's state variables and incoming ports
     ProdConsFlows.Container_i_GumboX.D_Inv_Guard_Container_i(api_b_event_data_in) & 
     ProdConsFlows.Container_i_GumboX.D_Inv_Guard_Container_i(api_c_event_data_in) & 
     ProdConsFlows.Container_i_GumboX.D_Inv_Container_i(api_a_data_in) & 

     // I-Assm-Guard: Integration constraints for filterp's incoming ports
     I_Assm_Guard_a_data_in(api_a_data_in) & 
     I_Assm_Guard_b_event_data_in(api_b_event_data_in))

  /** CEP-Pre: Compute Entrypoint Pre-Condition for filterp via container
    *
    * @param pre Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def compute_CEP_Pre_Container(pre: Filter_p_p_filterp_PreState_Container_PS): B =
    compute_CEP_Pre(
      api_d_event_in = pre.api_d_event_in,
      api_b_event_data_in = pre.api_b_event_data_in,
      api_c_event_data_in = pre.api_c_event_data_in,
      api_a_data_in = pre.api_a_data_in)

  /** guarantee data_in
    *   a_data_in 'flows to' e_data_out
    * @param api_a_data_in incoming data port
    * @param api_e_data_out outgoing data port
    */
  @strictpure def compute_case_data_in(
      api_a_data_in: ProdConsFlows.Container_i,
      api_e_data_out: ProdConsFlows.Container_i): B =
    (T) -->:
      (api_a_data_in == api_e_data_out)

  /** guarantee b_event_data
    *   If an event was received on b then its value
    *   is propagated to f
    * @param api_b_event_data_in incoming event data port
    * @param api_f_event_data_out outgoing event data port
    */
  @strictpure def compute_case_b_event_data(
      api_b_event_data_in: Option[ProdConsFlows.Container_i],
      api_f_event_data_out: Option[ProdConsFlows.Container_i]): B =
    (api_b_event_data_in.nonEmpty) -->:
      (api_f_event_data_out.nonEmpty &&
         api_f_event_data_out.get.value == api_b_event_data_in.get.value)

  /** CEP-T-Case: Top-Level case contracts for filterp's compute entrypoint
    *
    * @param api_b_event_data_in incoming event data port
    * @param api_a_data_in incoming data port
    * @param api_f_event_data_out outgoing event data port
    * @param api_e_data_out outgoing data port
    */
  @strictpure def compute_CEP_T_Case (
      api_b_event_data_in: Option[ProdConsFlows.Container_i],
      api_a_data_in: ProdConsFlows.Container_i,
      api_f_event_data_out: Option[ProdConsFlows.Container_i],
      api_e_data_out: ProdConsFlows.Container_i): B =
    compute_case_data_in(api_a_data_in, api_e_data_out) &
    compute_case_b_event_data(api_b_event_data_in, api_f_event_data_out)

  /** CEP-Post: Compute Entrypoint Post-Condition for filterp
    *
    * @param api_b_event_data_in incoming event data port
    * @param api_a_data_in incoming data port
    * @param api_h_event_out outgoing event port
    * @param api_f_event_data_out outgoing event data port
    * @param api_g_event_data_out outgoing event data port
    * @param api_e_data_out outgoing data port
    */
  @strictpure def compute_CEP_Post (
      api_b_event_data_in: Option[ProdConsFlows.Container_i],
      api_a_data_in: ProdConsFlows.Container_i,
      api_h_event_out: Option[art.Empty],
      api_f_event_data_out: Option[ProdConsFlows.Container_i],
      api_g_event_data_out: Option[ProdConsFlows.Container_i],
      api_e_data_out: ProdConsFlows.Container_i): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with filterp's state variables and outgoing ports
     ProdConsFlows.Container_i_GumboX.D_Inv_Guard_Container_i(api_f_event_data_out) & 
     ProdConsFlows.Container_i_GumboX.D_Inv_Guard_Container_i(api_g_event_data_out) & 
     ProdConsFlows.Container_i_GumboX.D_Inv_Container_i(api_e_data_out) & 

     // I-Guar-Guard: Integration constraints for filterp's outgoing ports
     I_Guar_e_data_out(api_e_data_out) & 
     I_Guar_Guard_f_event_data_out(api_f_event_data_out) & 

     // CEP-T-Case: case clauses of filterp's compute entrypoint
     compute_CEP_T_Case (api_b_event_data_in, api_a_data_in, api_f_event_data_out, api_e_data_out))

  /** CEP-Post: Compute Entrypoint Post-Condition for filterp via containers
    *
    * @param pre Container holding the values of incoming ports and the pre-state values of state variables
    * @param post Container holding the values of outgoing ports and the post-state values of state variables
    */
  @strictpure def compute_CEP_Post_Container(
      pre: Filter_p_p_filterp_PreState_Container_PS,
      post: Filter_p_p_filterp_PostState_Container_PS): B =
    compute_CEP_Post(
      api_b_event_data_in = pre.api_b_event_data_in,
      api_a_data_in = pre.api_a_data_in,
      api_h_event_out = post.api_h_event_out,
      api_f_event_data_out = post.api_f_event_data_out,
      api_g_event_data_out = post.api_g_event_data_out,
      api_e_data_out = post.api_e_data_out)
}
