#ifndef EXAMPLE_TYPES_HPP
#define EXAMPLE_TYPES_HPP

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include "isolette_cpp_pkg_interfaces/msg/tempimpl.hpp"
#include "isolette_cpp_pkg_interfaces/msg/physical_tempimpl.hpp"
#include "isolette_cpp_pkg_interfaces/msg/temp_wstatusimpl.hpp"
#include "isolette_cpp_pkg_interfaces/msg/failure_flagimpl.hpp"

static inline isolette_cpp_pkg_interfaces::msg::Tempimpl example_Tempimpl();
static inline isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl example_PhysicalTempimpl();
static inline isolette_cpp_pkg_interfaces::msg::TempWstatusimpl example_TempWstatusimpl();
static inline isolette_cpp_pkg_interfaces::msg::FailureFlagimpl example_FailureFlagimpl();

static inline isolette_cpp_pkg_interfaces::msg::Tempimpl example_Tempimpl() {
    isolette_cpp_pkg_interfaces::msg::Tempimpl msg;
    msg.value.data = 0.0f;
    return msg;
}

static inline isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl example_PhysicalTempimpl() {
    isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl msg;
    msg.value.data = 0.0f;
    return msg;
}

static inline isolette_cpp_pkg_interfaces::msg::TempWstatusimpl example_TempWstatusimpl() {
    isolette_cpp_pkg_interfaces::msg::TempWstatusimpl msg;
    msg.value.data = 0.0f;
    msg.status.value_status = isolette_cpp_pkg_interfaces::msg::ValueStatus::VALUE_STATUS_VALID;
    return msg;
}

static inline isolette_cpp_pkg_interfaces::msg::FailureFlagimpl example_FailureFlagimpl() {
    isolette_cpp_pkg_interfaces::msg::FailureFlagimpl msg;
    msg.value.data = false;
    return msg;
}

#endif  // EXAMPLE_TYPES_HPP
