#include "rclcpp/rclcpp.hpp"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/wheel_speed.hpp"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/empty.hpp"
#include "turtlesim/msg/pose.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/operating_mode.hpp"
#include "turtle_control_structure_cpp_pkg_interfaces/msg/trim_command.hpp"
#include <queue>
#include <sstream>
#include "turtle_control_structure_cpp_pkg/base_headers/enum_converter.hpp"
#include "turtle_control_structure_cpp_pkg/base_headers/example_types.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

static inline std::string _messageToString(const turtle_control_structure_cpp_pkg_interfaces::msg::WheelSpeed& msg) {
    std::ostringstream oss;
    oss << "WheelSpeed{rpm: " << msg.rpm.data << "}";
    return oss.str();
}

static inline std::string _messageToString(const turtle_control_structure_cpp_pkg_interfaces::msg::OperatingMode& msg) {
    std::ostringstream oss;
    oss << enumToString(msg);
    return oss.str();
}

static inline std::string _messageToString(const turtle_control_structure_cpp_pkg_interfaces::msg::TrimCommand& msg) {
    std::ostringstream oss;
    oss << "TrimCommand{delta_rpm: " << msg.delta_rpm.data << "}";
    return oss.str();
}

class proc_pilot_base : public rclcpp::Node
{
protected:
    proc_pilot_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================

    #define MESSAGE_TO_STRING(message) _messageToString(*message).c_str()
    #define PRINT_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define PRINT_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define PRINT_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)

    void put_cmdVel(geometry_msgs::msg::Twist msg);
    void put_mode(turtle_control_structure_cpp_pkg_interfaces::msg::OperatingMode msg);
    void put_calibrate();
    void put_trim(turtle_control_structure_cpp_pkg_interfaces::msg::TrimCommand msg);

    turtlesim::msg::Pose::SharedPtr get_pose();

    // Methods to be used to set initial values for data ports
    void init_pose(turtlesim::msg::Pose val);

private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;


    //=================================================
    //  C o m p u t e    E n t r y    P o i n t
    //=================================================
    virtual void handle_speed(const turtle_control_structure_cpp_pkg_interfaces::msg::WheelSpeed::SharedPtr msg) = 0;
    void event_handle_overspeed(const turtle_control_structure_cpp_pkg_interfaces::msg::Empty::SharedPtr msg);
    virtual void handle_overspeed() = 0;
    void handle_pose(const turtlesim::msg::Pose::SharedPtr msg);

    turtlesim::msg::Pose::SharedPtr pose_msg_holder;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<turtle_control_structure_cpp_pkg_interfaces::msg::WheelSpeed>::SharedPtr proc_pilot_speed_subscription_;
    rclcpp::Subscription<turtle_control_structure_cpp_pkg_interfaces::msg::Empty>::SharedPtr proc_pilot_overspeed_subscription_;
    rclcpp::Subscription<turtlesim::msg::Pose>::SharedPtr proc_pilot_pose_subscription_;

    rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr proc_pilot_cmdVel_publisher_;
    rclcpp::Publisher<turtle_control_structure_cpp_pkg_interfaces::msg::OperatingMode>::SharedPtr proc_pilot_mode_publisher_;
    rclcpp::Publisher<turtle_control_structure_cpp_pkg_interfaces::msg::Empty>::SharedPtr proc_pilot_calibrate_publisher_;
    rclcpp::Publisher<turtle_control_structure_cpp_pkg_interfaces::msg::TrimCommand>::SharedPtr proc_pilot_trim_publisher_;

};
