#ifndef ENUM_CONVERTER_HPP
#define ENUM_CONVERTER_HPP

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <string>
#include "isolette_cpp_pkg_interfaces/msg/value_status.hpp"
#include "isolette_cpp_pkg_interfaces/msg/regulator_mode.hpp"
#include "isolette_cpp_pkg_interfaces/msg/status.hpp"
#include "isolette_cpp_pkg_interfaces/msg/on_off.hpp"
#include "isolette_cpp_pkg_interfaces/msg/monitor_mode.hpp"
#include "isolette_cpp_pkg_interfaces/msg/heat.hpp"

const char* enumToString(isolette_cpp_pkg_interfaces::msg::ValueStatus* value);
const char* enumToString(isolette_cpp_pkg_interfaces::msg::RegulatorMode* value);
const char* enumToString(isolette_cpp_pkg_interfaces::msg::Status* value);
const char* enumToString(isolette_cpp_pkg_interfaces::msg::OnOff* value);
const char* enumToString(isolette_cpp_pkg_interfaces::msg::MonitorMode* value);
const char* enumToString(isolette_cpp_pkg_interfaces::msg::Heat* value);

#endif
