#include "fan_in_fan_out_system_cpp_pkg/base_headers/fanIn_consumer_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

fanIn_consumer_base::fanIn_consumer_base() : Node("fanIn_consumer")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    fanIn_consumer_myInteger_subscription_1 = this->create_subscription<fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64>(
        "fanIn_producer1_myInteger",
        1,
        std::bind(&fanIn_consumer_base::accept_myInteger, this, std::placeholders::_1), subscription_options_);

    fanIn_consumer_myInteger_subscription_2 = this->create_subscription<fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64>(
        "fanIn_producer2_myInteger",
        1,
        std::bind(&fanIn_consumer_base::accept_myInteger, this, std::placeholders::_1), subscription_options_);

    // Used by receiveInputs
    inDataPortTupleVector = {
    };

    // Used by sendOutputs
    outPortTupleVector = {
    };

}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void fanIn_consumer_base::accept_myInteger(fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64 msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_myInteger, msg);
    }
    std::thread([this]() {
        // One dispatch at a time.  This is what the old single mutex_ achieved by being
        // held for the whole lambda; it is kept separate so that the state lock can be
        // released around the entry point.
        std::lock_guard<std::mutex> dispatch(dispatch_mutex_);

        MsgType dispatched;
        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            receiveInputs(infrastructureIn_myInteger, applicationIn_myInteger);
            if (applicationIn_myInteger.empty()) return;
            dispatched = applicationIn_myInteger.front();
        }

        // Deliberately outside state_mutex_: the handler is user code and calls
        // put_<port>/get_<port>, which take that lock themselves.  The value stays on
        // applicationIn_myInteger until the handler returns, because get_myInteger
        // reads it from there.
        handle_myInteger_base(dispatched);

        {
            std::lock_guard<std::mutex> lock(state_mutex_);
            if (!applicationIn_myInteger.empty()) {
                applicationIn_myInteger.pop();
            }
        }

        sendOutputs();
    }).detach();
}

void fanIn_consumer_base::handle_myInteger_base(MsgType msg)
{
    if (auto typedMsg = std::get_if<fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64>(&msg)) {
        handle_myInteger(*typedMsg);
    } else {
        LOG_ERROR("Receiving wrong type of variable on port myInteger.\nThis shouldn't be possible.  If you are seeing this message, please notify this tool's current maintainer.");
    }
}

void fanIn_consumer_base::receiveInputs(std::queue<MsgType>& infrastructureQueue, std::queue<MsgType>& applicationQueue) {
    if (!infrastructureQueue.empty()) {
        MsgType eventMsg = infrastructureQueue.front();
        infrastructureQueue.pop();
        enqueue(applicationQueue, eventMsg);
    }

    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inDataPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            enqueue(*std::get<1>(port), msg);
        }
    }
}

void fanIn_consumer_base::enqueue(std::queue<MsgType>& queue, MsgType val) {
    if (queue.size() >= 1) {
        queue.pop();
    }
    queue.push(val);
}

void fanIn_consumer_base::sendOutputs() {
    // The queue work happens under state_mutex_; the publishing does not.  accept_<port>
    // runs from a subscription callback, so the middleware already holds locks of its own
    // when it takes state_mutex_.  Publishing while holding state_mutex_ would establish
    // the reverse order and put this lock into a cycle with the middleware's.  No such
    // cycle has been observed -- the lock-order inversions ThreadSanitizer reports here
    // are internal to Fast DDS and involve neither of this node's mutexes -- so this is
    // ordering hygiene rather than a fix for a diagnosed deadlock.  It also keeps the
    // critical section off the wire.  Collect first, release, then publish.
    std::vector<std::pair<void (fanIn_consumer_base::*)(MsgType), MsgType>> pending;
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (fanIn_consumer_base::*)(MsgType)> port : outPortTupleVector) {
            auto applicationQueue = std::get<0>(port);
            if (applicationQueue->size() != 0) {
                auto msg = applicationQueue->front();
                applicationQueue->pop();
                enqueue(*std::get<1>(port), msg);
            }
        }

        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (fanIn_consumer_base::*)(MsgType)> port : outPortTupleVector) {
            auto infrastructureQueue = std::get<1>(port);
            if (infrastructureQueue->size() != 0) {
                auto msg = infrastructureQueue->front();
                infrastructureQueue->pop();
                pending.emplace_back(std::get<2>(port), msg);
            }
        }
    }

    // Still one dispatch's worth of outputs, released together -- only the lock is gone.
    for (auto& entry : pending) {
        (this->*entry.first)(entry.second);
    }
}
