#include "fan_in_fan_out_system_cpp_pkg/base_headers/fanIn_producer1_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

fanIn_producer1_base::fanIn_producer1_base() : Node("fanIn_producer1")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    // Setting up connections
    fanIn_producer1_myInteger_publisher_ = this->create_publisher<fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64>(
        "fanIn_producer1_myInteger",
        1);

    // timeTriggeredCaller callback timer
    periodTimer_ = this->create_wall_timer(std::chrono::milliseconds(1000),
        std::bind(&fanIn_producer1_base::timeTriggeredCaller, this), cb_group_);

    // Used by receiveInputs
    inDataPortTupleVector = {
    };

    // Used by receiveInputs
    inEventPortTupleVector = {
    };

    // Used by sendOutputs
    outPortTupleVector = {
        {&applicationOut_myInteger, &infrastructureOut_myInteger, &fanIn_producer1_base::sendOut_myInteger}
    };

}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void fanIn_producer1_base::sendOut_myInteger(MsgType msg)
{
    if (auto typedMsg = std::get_if<fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64>(&msg)) {
        fanIn_producer1_myInteger_publisher_->publish(*typedMsg);
    } else {
        LOG_ERROR("Sending out wrong type of variable on port myInteger.\nThis shouldn't be possible.  If you are seeing this message, please notify this tool's current maintainer.");
    }
}

void fanIn_producer1_base::put_myInteger(fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64 msg)
{
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(applicationOut_myInteger, msg);
}

void fanIn_producer1_base::timeTriggeredCaller() {
    // One dispatch at a time: the callback group is Reentrant, so a period shorter than
    // the entry point would otherwise re-enter this concurrently.
    std::lock_guard<std::mutex> dispatch(dispatch_mutex_);

    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        receiveInputs();
    }

    // Deliberately outside state_mutex_: timeTriggered is user code and calls
    // put_<port>/get_<port>, which take that lock themselves.
    timeTriggered();

    sendOutputs();
}

void fanIn_producer1_base::receiveInputs() {
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inDataPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            enqueue(*std::get<1>(port), msg);
        }
    }
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inEventPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            infrastructureQueue->pop();
            enqueue(*std::get<1>(port), msg);
        }
    }
}

void fanIn_producer1_base::enqueue(std::queue<MsgType>& queue, MsgType val) {
    if (queue.size() >= 1) {
        queue.pop();
    }
    queue.push(val);
}

void fanIn_producer1_base::sendOutputs() {
    // The queue work happens under state_mutex_; the publishing does not.  accept_<port>
    // runs from a subscription callback, so the middleware already holds locks of its own
    // when it takes state_mutex_.  Publishing while holding state_mutex_ would establish
    // the reverse order and put this lock into a cycle with the middleware's.  No such
    // cycle has been observed -- the lock-order inversions ThreadSanitizer reports here
    // are internal to Fast DDS and involve neither of this node's mutexes -- so this is
    // ordering hygiene rather than a fix for a diagnosed deadlock.  It also keeps the
    // critical section off the wire.  Collect first, release, then publish.
    std::vector<std::pair<void (fanIn_producer1_base::*)(MsgType), MsgType>> pending;
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (fanIn_producer1_base::*)(MsgType)> port : outPortTupleVector) {
            auto applicationQueue = std::get<0>(port);
            if (applicationQueue->size() != 0) {
                auto msg = applicationQueue->front();
                applicationQueue->pop();
                enqueue(*std::get<1>(port), msg);
            }
        }

        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (fanIn_producer1_base::*)(MsgType)> port : outPortTupleVector) {
            auto infrastructureQueue = std::get<1>(port);
            if (infrastructureQueue->size() != 0) {
                auto msg = infrastructureQueue->front();
                infrastructureQueue->pop();
                pending.emplace_back(std::get<2>(port), msg);
            }
        }
    }

    // Still one dispatch's worth of outputs, released together -- only the lock is gone.
    for (auto& entry : pending) {
        (this->*entry.first)(entry.second);
    }
}
