#ifndef ENUM_CONVERTER_HPP
#define ENUM_CONVERTER_HPP

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

#include <string>
#include "building_control_cpp_pkg_interfaces/msg/temp_unit.hpp"
#include "building_control_cpp_pkg_interfaces/msg/fan_ack.hpp"
#include "building_control_cpp_pkg_interfaces/msg/fan_cmd.hpp"

const char* enumToString(const building_control_cpp_pkg_interfaces::msg::TempUnit& value);
const char* enumToString(const building_control_cpp_pkg_interfaces::msg::FanAck& value);
const char* enumToString(const building_control_cpp_pkg_interfaces::msg::FanCmd& value);

#endif
