// #Sireum

package TempControlSimpleTemp.TempSensor

import org.sireum._
import TempControlSimpleTemp._
import TempControlSimpleTemp.GumboXUtil.GumboXResult

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait TempSensor_i_tcproc_tempSensor_GumboX_TestHarness extends TempSensor_i_tcproc_tempSensor_TestApi {
  /** Contract-based test harness for the initialise entry point
    */
  def testInitialiseCB(
      ): GumboXResult.Type = {
    // [InvokeEntryPoint]: invoke the entry point test method
    testInitialise()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_tempChanged: Option[art.Empty] = get_tempChanged()
    val api_currentTemp: TempSensor.Temperature_i = get_currentTemp().get

    // [CheckPost]: invoke the oracle function
    val postResult = TempControlSimpleTemp.TempSensor.TempSensor_i_tcproc_tempSensor_GumboX.inititialize_IEP_Post(api_tempChanged, api_currentTemp)
    if (!postResult) {
      return GumboXResult.Post_Condition_Fail
    }

    return GumboXResult.Post_Condition_Pass
  }

  /** Contract-based test harness for the compute entry point
    */
  def testComputeCB(
      ): GumboXResult.Type = {
    // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved from the component state
    //   tempSensor does not have incoming ports or state variables

    // [CheckPre]: check/filter based on pre-condition.
    //   tempSensor's compute entry point does not have top level assume clauses

    // [PutInPorts]: put values on the input ports
    //   tempSensor does not have incoming ports

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_tempChanged: Option[art.Empty] = get_tempChanged()
    val api_currentTemp: TempSensor.Temperature_i = get_currentTemp().get

    // [CheckPost]: invoke the oracle function
    val postResult = TempControlSimpleTemp.TempSensor.TempSensor_i_tcproc_tempSensor_GumboX.compute_CEP_Post(api_tempChanged, api_currentTemp)
    if (!postResult) {
      return GumboXResult.Post_Condition_Fail
    }

    return GumboXResult.Post_Condition_Pass
  }
}
