#ifndef TCP_TEMPSENSOR_SRC_H
#define TCP_TEMPSENSOR_SRC_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

#include "temp_control_mixed_u_ros_microros_pkg/base_headers/tcp_tempSensor_base_src.h"

//=================================================
//  I n i t i a l i z e    E n t r y    P o i n t
//=================================================
void tcp_tempSensor_initialize(tcp_tempSensor_base_t * self);

//=================================================
//  C o m p u t e    E n t r y    P o i n t
//=================================================
void tcp_tempSensor_timeTriggered(tcp_tempSensor_base_t * self);

#endif  // TCP_TEMPSENSOR_SRC_H
