// #Sireum

package TempControlSimpleTemp.TempControlSoftwareSystem

import org.sireum._
import TempControlSimpleTemp._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
object TempControl_i_tcproc_tempControl_GumboX {
  /** I-Assm: Integration constraint on tempControl's incoming data port currentTemp
    *
    * assume currentTempRange
    */
  @strictpure def I_Assm_currentTemp(currentTemp: TempSensor.Temperature_i): B =
    currentTemp.degrees >= -128.6f &
      currentTemp.degrees <= 134.0f

  // I-Assm-Guard: Integration constraint on tempControl's incoming data port currentTemp
  @strictpure def I_Assm_Guard_currentTemp(currentTemp: TempSensor.Temperature_i): B =
    I_Assm_currentTemp(currentTemp)

  /** Initialize Entrypoint Contract
    *
    * guarantee defautSetPoint
    * @param currentSetPoint post-state state variable
    */
  @strictpure def initialize_defautSetPoint (
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i): B =
    currentSetPoint.low.degrees == 70.0f &&
      currentSetPoint.high.degrees == 80.0f

  /** Initialize Entrypoint Contract
    *
    * guarantee defaultFanStates
    * @param currentFanState post-state state variable
    */
  @strictpure def initialize_defaultFanStates (
      currentFanState: CoolingFan.FanCmd.Type): B =
    currentFanState == CoolingFan.FanCmd.Off

  /** Initialize Entrypoint Contract
    *
    * guarantee defaultLatestTemp
    * @param latestTemp post-state state variable
    */
  @strictpure def initialize_defaultLatestTemp (
      latestTemp: TempSensor.Temperature_i): B =
    latestTemp.degrees == 72.0f

  /** IEP-Guar: Initialize Entrypoint Contracts for tempControl
    *
    * @param currentFanState post-state state variable
    * @param currentSetPoint post-state state variable
    * @param latestTemp post-state state variable
    * @param api_fanCmd outgoing event data port
    */
  @strictpure def initialize_IEP_Guar (
      currentFanState: CoolingFan.FanCmd.Type,
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      latestTemp: TempSensor.Temperature_i,
      api_fanCmd: Option[CoolingFan.FanCmd.Type]): B =
    initialize_defautSetPoint(currentSetPoint) &
    initialize_defaultFanStates(currentFanState) &
    initialize_defaultLatestTemp(latestTemp)

  /** IEP-Post: Initialize Entrypoint Post-Condition
    *
    * @param currentFanState post-state state variable
    * @param currentSetPoint post-state state variable
    * @param latestTemp post-state state variable
    * @param api_fanCmd outgoing event data port
    */
  @strictpure def inititialize_IEP_Post (
      currentFanState: CoolingFan.FanCmd.Type,
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      latestTemp: TempSensor.Temperature_i,
      api_fanCmd: Option[CoolingFan.FanCmd.Type]): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with tempControl's state variables and outgoing ports
     TempControlSoftwareSystem.SetPoint_i.D_Inv_SetPoint_i(currentSetPoint) &
     TempSensor.Temperature_i.D_Inv_Temperature_i(latestTemp) & 

     // IEP-Guar: Initialize Entrypoint contract for tempControl
     initialize_IEP_Guar(currentFanState, currentSetPoint, latestTemp, api_fanCmd))

  /** IEP-Post: Initialize Entrypoint Post-Condition via container
    *
    * @param post Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def inititialize_IEP_Post_Container (post: TempControl_i_tcproc_tempControl_PostState_Container_PS): B =
    inititialize_IEP_Post (
      currentFanState = post.currentFanState,
      currentSetPoint = post.currentSetPoint,
      latestTemp = post.latestTemp,
      api_fanCmd = post.api_fanCmd)

  /** Compute Entrypoint Contract
    *
    * assumes a1
    *   If the previously received currentTemp was less than the previously
    *   received setPoint then the last fan command must have been Off
    * @param In_currentFanState pre-state state variable
    * @param In_currentSetPoint pre-state state variable
    * @param In_latestTemp pre-state state variable
    */
  @strictpure def compute_spec_a1_assume(
      In_currentFanState: CoolingFan.FanCmd.Type,
      In_currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      In_latestTemp: TempSensor.Temperature_i): B =
    In_latestTemp.degrees < In_currentSetPoint.low.degrees __>:
      In_currentFanState == CoolingFan.FanCmd.Off

  /** Compute Entrypoint Contract
    *
    * assumes a2
    *   If the previously received currentTemp was more than the previously
    *   received setPoint then the last fan command must have been On
    * @param In_currentFanState pre-state state variable
    * @param In_currentSetPoint pre-state state variable
    * @param In_latestTemp pre-state state variable
    */
  @strictpure def compute_spec_a2_assume(
      In_currentFanState: CoolingFan.FanCmd.Type,
      In_currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      In_latestTemp: TempSensor.Temperature_i): B =
    In_latestTemp.degrees > In_currentSetPoint.high.degrees __>:
      In_currentFanState == CoolingFan.FanCmd.On

  /** CEP-T-Assm: Top-level assume contracts for tempControl's compute entrypoint
    *
    * @param In_currentFanState pre-state state variable
    * @param In_currentSetPoint pre-state state variable
    * @param In_latestTemp pre-state state variable
    */
  @strictpure def compute_CEP_T_Assm (
      In_currentFanState: CoolingFan.FanCmd.Type,
      In_currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      In_latestTemp: TempSensor.Temperature_i): B =
    compute_spec_a1_assume(In_currentFanState, In_currentSetPoint, In_latestTemp) &
    compute_spec_a2_assume(In_currentFanState, In_currentSetPoint, In_latestTemp)

  /** CEP-Pre: Compute Entrypoint Pre-Condition for tempControl
    *
    * @param In_currentFanState pre-state state variable
    * @param In_currentSetPoint pre-state state variable
    * @param In_latestTemp pre-state state variable
    * @param api_tempChanged incoming event port
    * @param api_fanAck incoming event data port
    * @param api_setPoint incoming event data port
    * @param api_currentTemp incoming data port
    */
  @strictpure def compute_CEP_Pre (
      In_currentFanState: CoolingFan.FanCmd.Type,
      In_currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      In_latestTemp: TempSensor.Temperature_i,
      api_tempChanged: Option[art.Empty],
      api_fanAck: Option[CoolingFan.FanAck.Type],
      api_setPoint: Option[TempControlSoftwareSystem.SetPoint_i],
      api_currentTemp: TempSensor.Temperature_i): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with tempControl's state variables and incoming ports
     TempControlSoftwareSystem.SetPoint_i.D_Inv_SetPoint_i(In_currentSetPoint) & 
     TempSensor.Temperature_i.D_Inv_Temperature_i(In_latestTemp) & 
     TempControlSoftwareSystem.SetPoint_i.D_Inv_Guard_SetPoint_i(api_setPoint) & 
     TempSensor.Temperature_i.D_Inv_Temperature_i(api_currentTemp) & 

     // I-Assm-Guard: Integration constraints for tempControl's incoming ports
     I_Assm_Guard_currentTemp(api_currentTemp) & 

     // CEP-Assm: assume clauses of tempControl's compute entrypoint
     compute_CEP_T_Assm (In_currentFanState, In_currentSetPoint, In_latestTemp))

  /** CEP-Pre: Compute Entrypoint Pre-Condition for tempControl via container
    *
    * @param pre Container holding the value of incoming ports and the pre-state values of state variables
    */
  @strictpure def compute_CEP_Pre_Container(pre: TempControl_i_tcproc_tempControl_PreState_Container_PS): B =
    compute_CEP_Pre(
      In_currentFanState = pre.In_currentFanState,
      In_currentSetPoint = pre.In_currentSetPoint,
      In_latestTemp = pre.In_latestTemp,
      api_tempChanged = pre.api_tempChanged,
      api_fanAck = pre.api_fanAck,
      api_setPoint = pre.api_setPoint,
      api_currentTemp = pre.api_currentTemp)

  /** Compute Entrypoint Contract
    *
    * guarantee TC_Req_01
    *   If the current temperature is less than the set point, then the fan state shall be Off.
    * @param currentFanState post-state state variable
    * @param currentSetPoint post-state state variable
    * @param latestTemp post-state state variable
    */
  @strictpure def compute_spec_TC_Req_01_guarantee(
      currentFanState: CoolingFan.FanCmd.Type,
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      latestTemp: TempSensor.Temperature_i): B =
    latestTemp.degrees < currentSetPoint.low.degrees __>:
      currentFanState == CoolingFan.FanCmd.Off

  /** Compute Entrypoint Contract
    *
    * guarantee TC_Req_02
    *   If the current temperature is greater than the set point,
    *   then the fan state shall be On.
    * @param currentFanState post-state state variable
    * @param currentSetPoint post-state state variable
    * @param latestTemp post-state state variable
    */
  @strictpure def compute_spec_TC_Req_02_guarantee(
      currentFanState: CoolingFan.FanCmd.Type,
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      latestTemp: TempSensor.Temperature_i): B =
    latestTemp.degrees > currentSetPoint.high.degrees __>:
      currentFanState == CoolingFan.FanCmd.On

  /** CEP-T-Guar: Top-level guarantee contracts for tempControl's compute entrypoint
    *
    * @param currentFanState post-state state variable
    * @param currentSetPoint post-state state variable
    * @param latestTemp post-state state variable
    */
  @strictpure def compute_CEP_T_Guar (
      currentFanState: CoolingFan.FanCmd.Type,
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      latestTemp: TempSensor.Temperature_i): B =
    compute_spec_TC_Req_01_guarantee(currentFanState, currentSetPoint, latestTemp) &
    compute_spec_TC_Req_02_guarantee(currentFanState, currentSetPoint, latestTemp)

  /** Compute Entrypoint Contract for setPoint's setPointChanged guarantee clause
    *
    * guarantee setPointChanged
    * @param currentSetPoint post-state state variable
    * @param api_setPoint incoming event data port
    */
  @strictpure def compute_handle_setPoint_setPointChanged_guarantee(
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      api_setPoint: Option[TempControlSoftwareSystem.SetPoint_i]): B =
    currentSetPoint == api_setPoint.get

  /** CEP-T-Handle_setPoint_Guar: Top-level guarantee contracts for tempControl's compute setPoint handler
    *
    * @param currentSetPoint post-state state variable
    * @param api_setPoint incoming event data port
    */
  @strictpure def compute_CEP_Handler_setPoint_Guar (
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      api_setPoint: Option[TempControlSoftwareSystem.SetPoint_i]): B =
    api_setPoint.nonEmpty ___>: (
      compute_handle_setPoint_setPointChanged_guarantee(currentSetPoint, api_setPoint))

  /** Compute Entrypoint Contract for tempChanged's tempChanged guarantee clause
    *
    * guarantee tempChanged
    * @param latestTemp post-state state variable
    * @param api_currentTemp incoming data port
    */
  @strictpure def compute_handle_tempChanged_tempChanged_guarantee(
      latestTemp: TempSensor.Temperature_i,
      api_currentTemp: TempSensor.Temperature_i): B =
    latestTemp == api_currentTemp

  /** CEP-T-Handle_tempChanged_Guar: Top-level guarantee contracts for tempControl's compute tempChanged handler
    *
    * @param latestTemp post-state state variable
    * @param api_tempChanged incoming event port
    * @param api_currentTemp incoming data port
    */
  @strictpure def compute_CEP_Handler_tempChanged_Guar (
      latestTemp: TempSensor.Temperature_i,
      api_tempChanged: Option[art.Empty],
      api_currentTemp: TempSensor.Temperature_i): B =
    api_tempChanged.nonEmpty ___>: (
      compute_handle_tempChanged_tempChanged_guarantee(latestTemp, api_currentTemp))

  /** CEP-Post: Compute Entrypoint Post-Condition for tempControl
    *
    * @param In_currentFanState pre-state state variable
    * @param In_currentSetPoint pre-state state variable
    * @param In_latestTemp pre-state state variable
    * @param currentFanState post-state state variable
    * @param currentSetPoint post-state state variable
    * @param latestTemp post-state state variable
    * @param api_tempChanged incoming event port
    * @param api_fanAck incoming event data port
    * @param api_setPoint incoming event data port
    * @param api_currentTemp incoming data port
    * @param api_fanCmd outgoing event data port
    */
  @strictpure def compute_CEP_Post (
      In_currentFanState: CoolingFan.FanCmd.Type,
      In_currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      In_latestTemp: TempSensor.Temperature_i,
      currentFanState: CoolingFan.FanCmd.Type,
      currentSetPoint: TempControlSoftwareSystem.SetPoint_i,
      latestTemp: TempSensor.Temperature_i,
      api_tempChanged: Option[art.Empty],
      api_fanAck: Option[CoolingFan.FanAck.Type],
      api_setPoint: Option[TempControlSoftwareSystem.SetPoint_i],
      api_currentTemp: TempSensor.Temperature_i,
      api_fanCmd: Option[CoolingFan.FanCmd.Type]): B =
    (// D-Inv-Guard: Datatype invariants for the types associated with tempControl's state variables and outgoing ports
     TempControlSoftwareSystem.SetPoint_i.D_Inv_SetPoint_i(In_currentSetPoint) & 
     TempSensor.Temperature_i.D_Inv_Temperature_i(In_latestTemp) & 
     TempControlSoftwareSystem.SetPoint_i.D_Inv_SetPoint_i(currentSetPoint) & 
     TempSensor.Temperature_i.D_Inv_Temperature_i(latestTemp) & 
     TempControlSoftwareSystem.SetPoint_i.D_Inv_Guard_SetPoint_i(api_setPoint) & 
     TempSensor.Temperature_i.D_Inv_Temperature_i(api_currentTemp) & 

     // CEP-Guar: guarantee clauses of tempControl's compute entrypoint
     compute_CEP_T_Guar (currentFanState, currentSetPoint, latestTemp) & 

     // CEP-T-Handlers: handler clauses of tempControl's compute entrypoint
     compute_CEP_Handler_setPoint_Guar (currentSetPoint, api_setPoint) & 
     compute_CEP_Handler_tempChanged_Guar (latestTemp, api_tempChanged, api_currentTemp))

  /** CEP-Post: Compute Entrypoint Post-Condition for tempControl via containers
    *
    * @param pre Container holding the values of incoming ports and the pre-state values of state variables
    * @param post Container holding the values of outgoing ports and the post-state values of state variables
    */
  @strictpure def compute_CEP_Post_Container(
      pre: TempControl_i_tcproc_tempControl_PreState_Container_PS,
      post: TempControl_i_tcproc_tempControl_PostState_Container_PS): B =
    compute_CEP_Post(
      In_currentFanState = pre.In_currentFanState,
      In_currentSetPoint = pre.In_currentSetPoint,
      In_latestTemp = pre.In_latestTemp,
      currentFanState = post.currentFanState,
      currentSetPoint = post.currentSetPoint,
      latestTemp = post.latestTemp,
      api_tempChanged = pre.api_tempChanged,
      api_fanAck = pre.api_fanAck,
      api_setPoint = pre.api_setPoint,
      api_currentTemp = pre.api_currentTemp,
      api_fanCmd = post.api_fanCmd)
}
