// #Sireum

package tc.CoolingFan

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

@enum object FanCmd {
  "On"
  "Off"
}

object FanCmd_Payload {
  def example(): FanCmd_Payload = {
    return FanCmd_Payload(CoolingFan.FanCmd.On)
  }
}

@datatype class FanCmd_Payload(value: CoolingFan.FanCmd.Type) extends art.DataContent
