// #Sireum

package tc.TempSensor

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

@enum object Unit {
  "Kelvin"
  "Celsius"
  "Fahrenheit"
}

object Unit_Payload {
  def example(): Unit_Payload = {
    return Unit_Payload(TempSensor.Unit.Kelvin)
  }
}

@datatype class Unit_Payload(value: TempSensor.Unit.Type) extends art.DataContent
