#include "isolette_cpp_pkg/base_headers/temperature_sensor_cpi_thermostat_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

temperature_sensor_cpi_thermostat_base::temperature_sensor_cpi_thermostat_base() : Node("temperature_sensor_cpi_thermostat")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    temperature_sensor_cpi_thermostat_air_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl>(
        "temperature_sensor_cpi_thermostat_air",
        1,
        std::bind(&temperature_sensor_cpi_thermostat_base::accept_air, this, std::placeholders::_1), subscription_options_);

    temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_1 = this->create_publisher<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "thermostat_monitor_temperature_manage_monitor_interface_mmit_current_tempWstatus",
        1);

    temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_2 = this->create_publisher<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "thermostat_monitor_temperature_manage_alarm_mat_current_tempWstatus",
        1);

    temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_3 = this->create_publisher<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "thermostat_monitor_temperature_manage_monitor_mode_mmmt_current_tempWstatus",
        1);

    temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_4 = this->create_publisher<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "thermostat_regulate_temperature_manage_regulator_interface_mrit_current_tempWstatus",
        1);

    temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_5 = this->create_publisher<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "thermostat_regulate_temperature_manage_heat_source_mhst_current_tempWstatus",
        1);

    temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_6 = this->create_publisher<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "thermostat_regulate_temperature_manage_regulator_mode_mrmt_current_tempWstatus",
        1);

    // timeTriggeredCaller callback timer
    periodTimer_ = this->create_wall_timer(std::chrono::milliseconds(1000),
        std::bind(&temperature_sensor_cpi_thermostat_base::timeTriggeredCaller, this), cb_group_);

    // Used by receiveInputs
    inDataPortTupleVector = {
        {&infrastructureIn_air, &applicationIn_air}
    };

    // Used by receiveInputs
    inEventPortTupleVector = {
        {&infrastructureIn_air, &applicationIn_air}
    };

    // Used by sendOutputs
    outPortTupleVector = {
        {&applicationOut_current_tempWstatus, &infrastructureOut_current_tempWstatus, &temperature_sensor_cpi_thermostat_base::sendOut_current_tempWstatus}
    };

}

void temperature_sensor_cpi_thermostat_base::init_air(isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_air, val);
}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void temperature_sensor_cpi_thermostat_base::accept_air(isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_air, msg);
    }
}

isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl temperature_sensor_cpi_thermostat_base::get_air() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_air.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::PhysicalTempimpl>(msg);
}

void temperature_sensor_cpi_thermostat_base::sendOut_current_tempWstatus(MsgType msg)
{
    if (auto typedMsg = std::get_if<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(&msg)) {
        temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_1->publish(*typedMsg);
        temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_2->publish(*typedMsg);
        temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_3->publish(*typedMsg);
        temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_4->publish(*typedMsg);
        temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_5->publish(*typedMsg);
        temperature_sensor_cpi_thermostat_current_tempWstatus_publisher_6->publish(*typedMsg);
    } else {
        LOG_ERROR("Sending out wrong type of variable on port current_tempWstatus.\nThis shouldn't be possible.  If you are seeing this message, please notify this tool's current maintainer.");
    }
}

void temperature_sensor_cpi_thermostat_base::put_current_tempWstatus(isolette_cpp_pkg_interfaces::msg::TempWstatusimpl msg)
{
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(applicationOut_current_tempWstatus, msg);
}

void temperature_sensor_cpi_thermostat_base::timeTriggeredCaller() {
    // One dispatch at a time: the callback group is Reentrant, so a period shorter than
    // the entry point would otherwise re-enter this concurrently.
    std::lock_guard<std::mutex> dispatch(dispatch_mutex_);

    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        receiveInputs();
    }

    // Deliberately outside state_mutex_: timeTriggered is user code and calls
    // put_<port>/get_<port>, which take that lock themselves.
    timeTriggered();

    sendOutputs();
}

void temperature_sensor_cpi_thermostat_base::receiveInputs() {
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inDataPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            enqueue(*std::get<1>(port), msg);
        }
    }
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inEventPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            infrastructureQueue->pop();
            enqueue(*std::get<1>(port), msg);
        }
    }
}

void temperature_sensor_cpi_thermostat_base::enqueue(std::queue<MsgType>& queue, MsgType val) {
    if (queue.size() >= 1) {
        queue.pop();
    }
    queue.push(val);
}

void temperature_sensor_cpi_thermostat_base::sendOutputs() {
    // The queue work happens under state_mutex_; the publishing does not.  accept_<port>
    // runs from a subscription callback, so the middleware already holds locks of its own
    // when it takes state_mutex_.  Publishing while holding state_mutex_ would establish
    // the reverse order and put this lock into a cycle with the middleware's.  No such
    // cycle has been observed -- the lock-order inversions ThreadSanitizer reports here
    // are internal to Fast DDS and involve neither of this node's mutexes -- so this is
    // ordering hygiene rather than a fix for a diagnosed deadlock.  It also keeps the
    // critical section off the wire.  Collect first, release, then publish.
    std::vector<std::pair<void (temperature_sensor_cpi_thermostat_base::*)(MsgType), MsgType>> pending;
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (temperature_sensor_cpi_thermostat_base::*)(MsgType)> port : outPortTupleVector) {
            auto applicationQueue = std::get<0>(port);
            if (applicationQueue->size() != 0) {
                auto msg = applicationQueue->front();
                applicationQueue->pop();
                enqueue(*std::get<1>(port), msg);
            }
        }

        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (temperature_sensor_cpi_thermostat_base::*)(MsgType)> port : outPortTupleVector) {
            auto infrastructureQueue = std::get<1>(port);
            if (infrastructureQueue->size() != 0) {
                auto msg = infrastructureQueue->front();
                infrastructureQueue->pop();
                pending.emplace_back(std::get<2>(port), msg);
            }
        }
    }

    // Still one dispatch's worth of outputs, released together -- only the lock is gone.
    for (auto& entry : pending) {
        (this->*entry.first)(entry.second);
    }
}
