#include "isolette_cpp_pkg/base_headers/thermostat_regulate_temperature_manage_regulator_mode_mrmt_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::thermostat_regulate_temperature_manage_regulator_mode_mrmt_base() : Node("thermostat_regulate_temperature_manage_regulator_mode_mrmt")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    thermostat_regulate_temperature_manage_regulator_mode_mrmt_current_tempWstatus_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "temperature_sensor_cpi_thermostat_current_tempWstatus",
        1,
        std::bind(&thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::accept_current_tempWstatus, this, std::placeholders::_1), subscription_options_);

    thermostat_regulate_temperature_manage_regulator_mode_mrmt_interface_failure_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::FailureFlagimpl>(
        "thermostat_regulate_temperature_manage_regulator_interface_mrit_interface_failure",
        1,
        std::bind(&thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::accept_interface_failure, this, std::placeholders::_1), subscription_options_);

    thermostat_regulate_temperature_manage_regulator_mode_mrmt_internal_failure_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::FailureFlagimpl>(
        "thermostat_regulate_temperature_manage_regulator_mode_mrmt_internal_failure",
        1,
        std::bind(&thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::accept_internal_failure, this, std::placeholders::_1), subscription_options_);

    thermostat_regulate_temperature_manage_regulator_mode_mrmt_regulator_mode_publisher_ = this->create_publisher<isolette_cpp_pkg_interfaces::msg::RegulatorMode>(
        "thermostat_regulate_temperature_manage_regulator_mode_mrmt_regulator_mode",
        1);

    // timeTriggeredCaller callback timer
    periodTimer_ = this->create_wall_timer(std::chrono::milliseconds(1000),
        std::bind(&thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::timeTriggeredCaller, this), cb_group_);

    // Used by receiveInputs
    inDataPortTupleVector = {
        {&infrastructureIn_current_tempWstatus, &applicationIn_current_tempWstatus},
        {&infrastructureIn_interface_failure, &applicationIn_interface_failure},
        {&infrastructureIn_internal_failure, &applicationIn_internal_failure}
    };

    // Used by receiveInputs
    inEventPortTupleVector = {
        {&infrastructureIn_current_tempWstatus, &applicationIn_current_tempWstatus},
        {&infrastructureIn_interface_failure, &applicationIn_interface_failure},
        {&infrastructureIn_internal_failure, &applicationIn_internal_failure}
    };

    // Used by sendOutputs
    outPortTupleVector = {
        {&applicationOut_regulator_mode, &infrastructureOut_regulator_mode, &thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::sendOut_regulator_mode}
    };

}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::init_current_tempWstatus(isolette_cpp_pkg_interfaces::msg::TempWstatusimpl val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_current_tempWstatus, val);
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::init_interface_failure(isolette_cpp_pkg_interfaces::msg::FailureFlagimpl val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_interface_failure, val);
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::init_internal_failure(isolette_cpp_pkg_interfaces::msg::FailureFlagimpl val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_internal_failure, val);
}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::accept_current_tempWstatus(isolette_cpp_pkg_interfaces::msg::TempWstatusimpl msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_current_tempWstatus, msg);
    }
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::accept_interface_failure(isolette_cpp_pkg_interfaces::msg::FailureFlagimpl msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_interface_failure, msg);
    }
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::accept_internal_failure(isolette_cpp_pkg_interfaces::msg::FailureFlagimpl msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_internal_failure, msg);
    }
}

isolette_cpp_pkg_interfaces::msg::TempWstatusimpl thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::get_current_tempWstatus() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_current_tempWstatus.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(msg);
}

isolette_cpp_pkg_interfaces::msg::FailureFlagimpl thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::get_interface_failure() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_interface_failure.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::FailureFlagimpl>(msg);
}

isolette_cpp_pkg_interfaces::msg::FailureFlagimpl thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::get_internal_failure() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_internal_failure.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::FailureFlagimpl>(msg);
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::sendOut_regulator_mode(MsgType msg)
{
    if (auto typedMsg = std::get_if<isolette_cpp_pkg_interfaces::msg::RegulatorMode>(&msg)) {
        thermostat_regulate_temperature_manage_regulator_mode_mrmt_regulator_mode_publisher_->publish(*typedMsg);
    } else {
        LOG_ERROR("Sending out wrong type of variable on port regulator_mode.\nThis shouldn't be possible.  If you are seeing this message, please notify this tool's current maintainer.");
    }
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::put_regulator_mode(isolette_cpp_pkg_interfaces::msg::RegulatorMode msg)
{
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(applicationOut_regulator_mode, msg);
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::timeTriggeredCaller() {
    // One dispatch at a time: the callback group is Reentrant, so a period shorter than
    // the entry point would otherwise re-enter this concurrently.
    std::lock_guard<std::mutex> dispatch(dispatch_mutex_);

    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        receiveInputs();
    }

    // Deliberately outside state_mutex_: timeTriggered is user code and calls
    // put_<port>/get_<port>, which take that lock themselves.
    timeTriggered();

    sendOutputs();
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::receiveInputs() {
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inDataPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            enqueue(*std::get<1>(port), msg);
        }
    }
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inEventPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            infrastructureQueue->pop();
            enqueue(*std::get<1>(port), msg);
        }
    }
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::enqueue(std::queue<MsgType>& queue, MsgType val) {
    if (queue.size() >= 1) {
        queue.pop();
    }
    queue.push(val);
}

void thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::sendOutputs() {
    // The queue work happens under state_mutex_; the publishing does not.  accept_<port>
    // runs from a subscription callback, so the middleware already holds locks of its own
    // when it takes state_mutex_.  Publishing while holding state_mutex_ would establish
    // the reverse order and put this lock into a cycle with the middleware's.  No such
    // cycle has been observed -- the lock-order inversions ThreadSanitizer reports here
    // are internal to Fast DDS and involve neither of this node's mutexes -- so this is
    // ordering hygiene rather than a fix for a diagnosed deadlock.  It also keeps the
    // critical section off the wire.  Collect first, release, then publish.
    std::vector<std::pair<void (thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::*)(MsgType), MsgType>> pending;
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::*)(MsgType)> port : outPortTupleVector) {
            auto applicationQueue = std::get<0>(port);
            if (applicationQueue->size() != 0) {
                auto msg = applicationQueue->front();
                applicationQueue->pop();
                enqueue(*std::get<1>(port), msg);
            }
        }

        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (thermostat_regulate_temperature_manage_regulator_mode_mrmt_base::*)(MsgType)> port : outPortTupleVector) {
            auto infrastructureQueue = std::get<1>(port);
            if (infrastructureQueue->size() != 0) {
                auto msg = infrastructureQueue->front();
                infrastructureQueue->pop();
                pending.emplace_back(std::get<2>(port), msg);
            }
        }
    }

    // Still one dispatch's worth of outputs, released together -- only the lock is gone.
    for (auto& entry : pending) {
        (this->*entry.first)(entry.second);
    }
}
