#include "isolette_cpp_pkg/base_headers/thermostat_monitor_temperature_manage_alarm_mat_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

thermostat_monitor_temperature_manage_alarm_mat_base::thermostat_monitor_temperature_manage_alarm_mat_base() : Node("thermostat_monitor_temperature_manage_alarm_mat")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    thermostat_monitor_temperature_manage_alarm_mat_current_tempWstatus_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(
        "temperature_sensor_cpi_thermostat_current_tempWstatus",
        1,
        std::bind(&thermostat_monitor_temperature_manage_alarm_mat_base::accept_current_tempWstatus, this, std::placeholders::_1), subscription_options_);

    thermostat_monitor_temperature_manage_alarm_mat_lower_alarm_temp_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::Tempimpl>(
        "thermostat_monitor_temperature_manage_monitor_interface_mmit_lower_alarm_temp",
        1,
        std::bind(&thermostat_monitor_temperature_manage_alarm_mat_base::accept_lower_alarm_temp, this, std::placeholders::_1), subscription_options_);

    thermostat_monitor_temperature_manage_alarm_mat_upper_alarm_temp_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::Tempimpl>(
        "thermostat_monitor_temperature_manage_monitor_interface_mmit_upper_alarm_temp",
        1,
        std::bind(&thermostat_monitor_temperature_manage_alarm_mat_base::accept_upper_alarm_temp, this, std::placeholders::_1), subscription_options_);

    thermostat_monitor_temperature_manage_alarm_mat_monitor_mode_subscription_ = this->create_subscription<isolette_cpp_pkg_interfaces::msg::MonitorMode>(
        "thermostat_monitor_temperature_manage_monitor_mode_mmmt_monitor_mode",
        1,
        std::bind(&thermostat_monitor_temperature_manage_alarm_mat_base::accept_monitor_mode, this, std::placeholders::_1), subscription_options_);

    thermostat_monitor_temperature_manage_alarm_mat_alarm_control_publisher_ = this->create_publisher<isolette_cpp_pkg_interfaces::msg::OnOff>(
        "thermostat_monitor_temperature_manage_alarm_mat_alarm_control",
        1);

    // timeTriggeredCaller callback timer
    periodTimer_ = this->create_wall_timer(std::chrono::milliseconds(1000),
        std::bind(&thermostat_monitor_temperature_manage_alarm_mat_base::timeTriggeredCaller, this), cb_group_);

    // Used by receiveInputs
    inDataPortTupleVector = {
        {&infrastructureIn_current_tempWstatus, &applicationIn_current_tempWstatus},
        {&infrastructureIn_lower_alarm_temp, &applicationIn_lower_alarm_temp},
        {&infrastructureIn_upper_alarm_temp, &applicationIn_upper_alarm_temp},
        {&infrastructureIn_monitor_mode, &applicationIn_monitor_mode}
    };

    // Used by receiveInputs
    inEventPortTupleVector = {
        {&infrastructureIn_current_tempWstatus, &applicationIn_current_tempWstatus},
        {&infrastructureIn_lower_alarm_temp, &applicationIn_lower_alarm_temp},
        {&infrastructureIn_upper_alarm_temp, &applicationIn_upper_alarm_temp},
        {&infrastructureIn_monitor_mode, &applicationIn_monitor_mode}
    };

    // Used by sendOutputs
    outPortTupleVector = {
        {&applicationOut_alarm_control, &infrastructureOut_alarm_control, &thermostat_monitor_temperature_manage_alarm_mat_base::sendOut_alarm_control}
    };

}

void thermostat_monitor_temperature_manage_alarm_mat_base::init_current_tempWstatus(isolette_cpp_pkg_interfaces::msg::TempWstatusimpl val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_current_tempWstatus, val);
}

void thermostat_monitor_temperature_manage_alarm_mat_base::init_lower_alarm_temp(isolette_cpp_pkg_interfaces::msg::Tempimpl val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_lower_alarm_temp, val);
}

void thermostat_monitor_temperature_manage_alarm_mat_base::init_upper_alarm_temp(isolette_cpp_pkg_interfaces::msg::Tempimpl val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_upper_alarm_temp, val);
}

void thermostat_monitor_temperature_manage_alarm_mat_base::init_monitor_mode(isolette_cpp_pkg_interfaces::msg::MonitorMode val) {
    // Reachable from the initialize entry point.  That runs during construction, before
    // the executor spins, so there is no contention -- the lock is taken anyway to keep
    // one rule: anything user code can call takes state_mutex_.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(infrastructureIn_monitor_mode, val);
}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void thermostat_monitor_temperature_manage_alarm_mat_base::accept_current_tempWstatus(isolette_cpp_pkg_interfaces::msg::TempWstatusimpl msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_current_tempWstatus, msg);
    }
}

void thermostat_monitor_temperature_manage_alarm_mat_base::accept_lower_alarm_temp(isolette_cpp_pkg_interfaces::msg::Tempimpl msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_lower_alarm_temp, msg);
    }
}

void thermostat_monitor_temperature_manage_alarm_mat_base::accept_upper_alarm_temp(isolette_cpp_pkg_interfaces::msg::Tempimpl msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_upper_alarm_temp, msg);
    }
}

void thermostat_monitor_temperature_manage_alarm_mat_base::accept_monitor_mode(isolette_cpp_pkg_interfaces::msg::MonitorMode msg)
{
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        enqueue(infrastructureIn_monitor_mode, msg);
    }
}

isolette_cpp_pkg_interfaces::msg::TempWstatusimpl thermostat_monitor_temperature_manage_alarm_mat_base::get_current_tempWstatus() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_current_tempWstatus.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::TempWstatusimpl>(msg);
}

isolette_cpp_pkg_interfaces::msg::Tempimpl thermostat_monitor_temperature_manage_alarm_mat_base::get_lower_alarm_temp() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_lower_alarm_temp.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::Tempimpl>(msg);
}

isolette_cpp_pkg_interfaces::msg::Tempimpl thermostat_monitor_temperature_manage_alarm_mat_base::get_upper_alarm_temp() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_upper_alarm_temp.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::Tempimpl>(msg);
}

isolette_cpp_pkg_interfaces::msg::MonitorMode thermostat_monitor_temperature_manage_alarm_mat_base::get_monitor_mode() {
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    MsgType msg = applicationIn_monitor_mode.front();
    return std::get<isolette_cpp_pkg_interfaces::msg::MonitorMode>(msg);
}

void thermostat_monitor_temperature_manage_alarm_mat_base::sendOut_alarm_control(MsgType msg)
{
    if (auto typedMsg = std::get_if<isolette_cpp_pkg_interfaces::msg::OnOff>(&msg)) {
        thermostat_monitor_temperature_manage_alarm_mat_alarm_control_publisher_->publish(*typedMsg);
    } else {
        LOG_ERROR("Sending out wrong type of variable on port alarm_control.\nThis shouldn't be possible.  If you are seeing this message, please notify this tool's current maintainer.");
    }
}

void thermostat_monitor_temperature_manage_alarm_mat_base::put_alarm_control(isolette_cpp_pkg_interfaces::msg::OnOff msg)
{
    // Called from the compute entry point, which runs without state_mutex_ held.
    std::lock_guard<std::mutex> lock(state_mutex_);
    enqueue(applicationOut_alarm_control, msg);
}

void thermostat_monitor_temperature_manage_alarm_mat_base::timeTriggeredCaller() {
    // One dispatch at a time: the callback group is Reentrant, so a period shorter than
    // the entry point would otherwise re-enter this concurrently.
    std::lock_guard<std::mutex> dispatch(dispatch_mutex_);

    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        receiveInputs();
    }

    // Deliberately outside state_mutex_: timeTriggered is user code and calls
    // put_<port>/get_<port>, which take that lock themselves.
    timeTriggered();

    sendOutputs();
}

void thermostat_monitor_temperature_manage_alarm_mat_base::receiveInputs() {
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inDataPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            enqueue(*std::get<1>(port), msg);
        }
    }
    for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*> port : inEventPortTupleVector) {
        auto infrastructureQueue = std::get<0>(port);
        if (!infrastructureQueue->empty()) {
            auto msg = infrastructureQueue->front();
            infrastructureQueue->pop();
            enqueue(*std::get<1>(port), msg);
        }
    }
}

void thermostat_monitor_temperature_manage_alarm_mat_base::enqueue(std::queue<MsgType>& queue, MsgType val) {
    if (queue.size() >= 1) {
        queue.pop();
    }
    queue.push(val);
}

void thermostat_monitor_temperature_manage_alarm_mat_base::sendOutputs() {
    // The queue work happens under state_mutex_; the publishing does not.  accept_<port>
    // runs from a subscription callback, so the middleware already holds locks of its own
    // when it takes state_mutex_.  Publishing while holding state_mutex_ would establish
    // the reverse order and put this lock into a cycle with the middleware's.  No such
    // cycle has been observed -- the lock-order inversions ThreadSanitizer reports here
    // are internal to Fast DDS and involve neither of this node's mutexes -- so this is
    // ordering hygiene rather than a fix for a diagnosed deadlock.  It also keeps the
    // critical section off the wire.  Collect first, release, then publish.
    std::vector<std::pair<void (thermostat_monitor_temperature_manage_alarm_mat_base::*)(MsgType), MsgType>> pending;
    {
        std::lock_guard<std::mutex> lock(state_mutex_);
        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (thermostat_monitor_temperature_manage_alarm_mat_base::*)(MsgType)> port : outPortTupleVector) {
            auto applicationQueue = std::get<0>(port);
            if (applicationQueue->size() != 0) {
                auto msg = applicationQueue->front();
                applicationQueue->pop();
                enqueue(*std::get<1>(port), msg);
            }
        }

        for (std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (thermostat_monitor_temperature_manage_alarm_mat_base::*)(MsgType)> port : outPortTupleVector) {
            auto infrastructureQueue = std::get<1>(port);
            if (infrastructureQueue->size() != 0) {
                auto msg = infrastructureQueue->front();
                infrastructureQueue->pop();
                pending.emplace_back(std::get<2>(port), msg);
            }
        }
    }

    // Still one dispatch's worth of outputs, released together -- only the lock is gone.
    for (auto& entry : pending) {
        (this->*entry.first)(entry.second);
    }
}
