#include "rclcpp/rclcpp.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/temperature.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/set_point.hpp"
#include <queue>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

class tcp_opInterface_base : public rclcpp::Node
{
protected:
    tcp_opInterface_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================

    #define MESSAGE_TO_STRING(message) temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::to_yaml(*message).c_str()
    #define PRINT_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define PRINT_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define PRINT_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)

    void put_setPoint(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint msg);

    temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature::SharedPtr get_currentTemp();

    // Methods to be used to set initial values for data ports
    void init_currentTemp(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature val);

private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;


    //=================================================
    //  C o m p u t e    E n t r y    P o i n t
    //=================================================
    void handle_currentTemp(const temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature::SharedPtr msg);

    temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature::SharedPtr currentTemp_msg_holder;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature>::SharedPtr tcp_opInterface_currentTemp_subscription_;

    rclcpp::Publisher<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint>::SharedPtr tcp_opInterface_setPoint_publisher_;

    //=================================================
    //  C a l l b a c k   a n d   T i m e r
    //=================================================
    virtual void timeTriggered() = 0;

    rclcpp::TimerBase::SharedPtr periodTimer_;

};
