#include "temp_control_mixed_u_ros_cpp_pkg/base_headers/tcp_opInterface_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

tcp_opInterface_base::tcp_opInterface_base() : Node("tcp_opInterface")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    tcp_opInterface_currentTemp_subscription_ = this->create_subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature>(
        "tcp_opInterface_currentTemp",
        1,
        std::bind(&tcp_opInterface_base::handle_currentTemp, this, std::placeholders::_1), subscription_options_);

    tcp_opInterface_setPoint_publisher_ = this->create_publisher<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint>(
        "tcp_tempControl_setPoint",
        1);

    // timeTriggered callback timer
    periodTimer_ = this->create_wall_timer(std::chrono::milliseconds(1000),
        std::bind(&tcp_opInterface_base::timeTriggered, this), cb_group_);

}

void tcp_opInterface_base::init_currentTemp(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature val) {
    currentTemp_msg_holder = std::make_shared<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature>(val);
}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void tcp_opInterface_base::handle_currentTemp(const temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature::SharedPtr msg)
{
    currentTemp_msg_holder = msg;
}

temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature::SharedPtr tcp_opInterface_base::get_currentTemp() {
    return currentTemp_msg_holder;
}

void tcp_opInterface_base::put_setPoint(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint msg)
{
    tcp_opInterface_setPoint_publisher_->publish(msg);
}

