#include "temp_control_mixed_u_ros_cpp_pkg/base_headers/tcp_fan_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

tcp_fan_base::tcp_fan_base() : Node("tcp_fan")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    tcp_fan_fanCmd_subscription_ = this->create_subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd>(
        "tcp_fan_fanCmd",
        1,
        std::bind(&tcp_fan_base::handle_fanCmd, this, std::placeholders::_1), subscription_options_);

    tcp_fan_fanAck_publisher_ = this->create_publisher<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck>(
        "tcp_tempControl_fanAck",
        1);

    // timeTriggered callback timer
    periodTimer_ = this->create_wall_timer(std::chrono::milliseconds(1000),
        std::bind(&tcp_fan_base::timeTriggered, this), cb_group_);

}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void tcp_fan_base::handle_fanCmd(const temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd::SharedPtr msg)
{
    fanCmd_msg_holder = msg;
}

temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd::SharedPtr tcp_fan_base::get_fanCmd() {
    return fanCmd_msg_holder;
}

void tcp_fan_base::put_fanAck(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck msg)
{
    tcp_fan_fanAck_publisher_->publish(msg);
}

