#include "uros_demo_gumbo_cpp_pkg/base_headers/proc_logger_base_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

proc_logger_base::proc_logger_base() : Node("proc_logger", "uros_demo")
{
    cb_group_ = this->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
    subscription_options_.callback_group = cb_group_;

    // Setting up connections
    proc_logger_rosout_subscription_ = this->create_subscription<rcl_interfaces::msg::Log>(
        "/rosout",
        1,
        std::bind(&proc_logger_base::handle_rosout, this, std::placeholders::_1), subscription_options_);

}
