// #Sireum
package TempControlSimpleTemp

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

object GumboXUtil {

  @enum object GumboXResult {
    "Pre_Condition_Unsat"
    "Post_Condition_Pass"
    "Post_Condition_Fail"
  }
}