#include "temp_control_mixed_u_ros_microros_pkg/base_headers/enum_converter.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

const char* enumToString_TempUnit(uint8_t value)
{
    switch (value) {
        case temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__TempUnit__TEMP_UNIT_FAHRENHEIT: return "Fahrenheit";
        case temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__TempUnit__TEMP_UNIT_CELSIUS: return "Celsius";
        case temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__TempUnit__TEMP_UNIT_KELVIN: return "Kelvin";
        default: return "Unknown";
    }
}

const char* enumToString_FanAck(uint8_t value)
{
    switch (value) {
        case temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__FanAck__FAN_ACK_OK: return "Ok";
        case temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__FanAck__FAN_ACK_ERROR: return "Error";
        default: return "Unknown";
    }
}

const char* enumToString_FanCmd(uint8_t value)
{
    switch (value) {
        case temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__FanCmd__FAN_CMD_ON: return "On";
        case temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__FanCmd__FAN_CMD_OFF: return "Off";
        default: return "Unknown";
    }
}

