#include "temp_control_mixed_u_ros_microros_pkg/base_headers/tcp_tempSensor_base_src.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

// Forward declaration of user compute entry point
void tcp_tempSensor_timeTriggered(tcp_tempSensor_base_t * self);

// Static instance pointer for timer callback context (heap-free, MCU-compatible)
static tcp_tempSensor_base_t * g_self = NULL;

//=================================================
//  C a l l b a c k   a n d   T i m e r
//=================================================

static void period_timer_callback(rcl_timer_t * timer, int64_t last_call_time)
{
    (void)timer;
    (void)last_call_time;
    if (g_self != NULL) {
        tcp_tempSensor_timeTriggered(g_self);
    }
}

//=================================================
//  I n i t i a l i z a t i o n
//=================================================

void tcp_tempSensor_base_init(tcp_tempSensor_base_t * self)
{
    g_self = self;

    self->allocator = rcl_get_default_allocator();

    rclc_support_init(&self->support, 0, NULL, &self->allocator);

    rclc_node_init_default(&self->node, "tcp_tempSensor", "", &self->support);

    // Setting up connections
    rclc_publisher_init_default(
        &self->tcp_tempSensor_currentTemp_publisher_1,
        &self->node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(temp_control_mixed_u_ros_cpp_pkg_interfaces, msg, Temperature),
        "tcp_tempControl_currentTemp");

    rclc_publisher_init_default(
        &self->tcp_tempSensor_currentTemp_publisher_2,
        &self->node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(temp_control_mixed_u_ros_cpp_pkg_interfaces, msg, Temperature),
        "tcp_opInterface_currentTemp");

    rclc_publisher_init_default(
        &self->tcp_tempSensor_tempChanged_publisher,
        &self->node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(temp_control_mixed_u_ros_cpp_pkg_interfaces, msg, Empty),
        "tcp_tempControl_tempChanged");

    // timeTriggered callback timer
    rclc_timer_init_default(
        &self->period_timer,
        &self->support,
        RCL_MS_TO_NS(1000),
        period_timer_callback);

    rclc_executor_init(&self->executor, &self->support.context, 1, &self->allocator);
    rclc_executor_add_timer(&self->executor, &self->period_timer);
}

void tcp_tempSensor_base_spin(tcp_tempSensor_base_t * self)
{
    rclc_executor_spin(&self->executor);
}

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void put_currentTemp(tcp_tempSensor_base_t * self, temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Temperature * msg)
{
    rcl_ret_t ret1 = rcl_publish(&self->tcp_tempSensor_currentTemp_publisher_1, msg, NULL);
    if (ret1 != RCL_RET_OK) {
        PRINT_ERROR("Failed to publish currentTemp (1)");
    }
    rcl_ret_t ret2 = rcl_publish(&self->tcp_tempSensor_currentTemp_publisher_2, msg, NULL);
    if (ret2 != RCL_RET_OK) {
        PRINT_ERROR("Failed to publish currentTemp (2)");
    }
}

void put_tempChanged(tcp_tempSensor_base_t * self)
{
    temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Empty msg;
    temp_control_mixed_u_ros_cpp_pkg_interfaces__msg__Empty__init(&msg);
    rcl_ret_t ret = rcl_publish(&self->tcp_tempSensor_tempChanged_publisher, &msg, NULL);
    if (ret != RCL_RET_OK) {
        PRINT_ERROR("Failed to publish tempChanged");
    }
}

