// #Sireum

package tc.util

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

@sig trait Container extends art.DataContent

@datatype class EmptyContainer extends Container
