#include "uros_demo_naming_microros_pkg/user_headers/proc_ttj_src.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

static proc_ttj_base_t node;

int main(int argc, char ** argv)
{
    (void)argc;
    (void)argv;

    // A failure here means the node could not create the entities it needs, so
    // spinning would busy-wait forever on a node that can never publish or
    // receive.  Exiting non-zero instead lets the launching layer notice.
    rcl_ret_t init_status = proc_ttj_base_init(&node);
    if (init_status != RCL_RET_OK) {
        PRINT_ERROR("proc_ttj initialization failed with status %d; aborting", (int) init_status);
        return 1;
    }

    // Invoke initialize entry point
    proc_ttj_initialize(&node);

    PRINT_INFO("proc_ttj infrastructure set up");

    proc_ttj_base_spin(&node);

    return 0;
}
