#ifndef ENUM_CONVERTER_HPP
#define ENUM_CONVERTER_HPP

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <string>
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/temp_unit.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/fan_ack.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/fan_cmd.hpp"

const char* enumToString(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::TempUnit value);
const char* enumToString(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck value);
const char* enumToString(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd value);

#endif
