#include "rclcpp/rclcpp.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/fan_cmd.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/fan_ack.hpp"
#include <queue>
#include <vector>
#include <variant>
#include <mutex>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

class tcp_fan_base : public rclcpp::Node
{
protected:
    using MsgType = std::variant<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd, temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck>;

    tcp_fan_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================

    #define MESSAGE_TO_STRING(message) temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::to_yaml(message).c_str()
    #define PRINT_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define PRINT_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define PRINT_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)

    void put_fanAck(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck msg);

    temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd get_fanCmd();

private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    void accept_fanCmd(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd msg);

    // Methods for working with port queues
    void receiveInputs();

    void sendOutputs();

    void enqueue(std::queue<MsgType>& queue, MsgType val);

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;

    std::queue<MsgType> infrastructureIn_fanCmd;
    std::queue<MsgType> applicationIn_fanCmd;

    std::queue<MsgType> infrastructureOut_fanAck;
    std::queue<MsgType> applicationOut_fanAck;

    void sendOut_fanAck(MsgType msg);

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd>::SharedPtr tcp_fan_fanCmd_subscription_;

    rclcpp::Publisher<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck>::SharedPtr tcp_fan_fanAck_publisher_;

    //=================================================
    //  C a l l b a c k   a n d   T i m e r
    //=================================================
    virtual void timeTriggered() = 0;

    rclcpp::TimerBase::SharedPtr periodTimer_;

    void timeTriggeredCaller();

    // Used for thread locking
    std::mutex mutex_;

    // Used by receiveInputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*>> inDataPortTupleVector;
    // Used by receiveInputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*>> inEventPortTupleVector;
    // Used by sendOutputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (tcp_fan_base::*)(MsgType)>> outPortTupleVector;
};
