#include "rclcpp/rclcpp.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/temperature.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/set_point.hpp"
#include <queue>
#include <sstream>
#include <vector>
#include <variant>
#include <mutex>
#include "temp_control_mixed_u_ros_cpp_pkg/base_headers/enum_converter.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg/base_headers/example_types.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

static inline std::string _messageToString(const temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature& msg) {
    std::ostringstream oss;
    oss << "Temperature{degrees: " << msg.degrees.data << ", unit: " << enumToString(msg.unit) << "}";
    return oss.str();
}

static inline std::string _messageToString(const temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint& msg) {
    std::ostringstream oss;
    oss << "SetPoint{low: " << "Temperature{degrees: " << msg.low.degrees.data << ", unit: " << enumToString(msg.low.unit) << "}" << ", high: " << "Temperature{degrees: " << msg.high.degrees.data << ", unit: " << enumToString(msg.high.unit) << "}" << "}";
    return oss.str();
}

class tcp_opInterface_base : public rclcpp::Node
{
protected:
    using MsgType = std::variant<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature, temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint>;

    tcp_opInterface_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================

    #define MESSAGE_TO_STRING(message) _messageToString(message).c_str()
    #define PRINT_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define PRINT_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define PRINT_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)

    void put_setPoint(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint msg);

    temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature get_currentTemp();

    // Methods to be used to set initial values for data ports
    void init_currentTemp(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature val);

private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    void accept_currentTemp(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature msg);

    // Methods for working with port queues
    void receiveInputs();

    void sendOutputs();

    void enqueue(std::queue<MsgType>& queue, MsgType val);

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;

    std::queue<MsgType> infrastructureIn_currentTemp;
    std::queue<MsgType> applicationIn_currentTemp;

    std::queue<MsgType> infrastructureOut_setPoint;
    std::queue<MsgType> applicationOut_setPoint;

    void sendOut_setPoint(MsgType msg);

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature>::SharedPtr tcp_opInterface_currentTemp_subscription_;

    rclcpp::Publisher<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint>::SharedPtr tcp_opInterface_setPoint_publisher_;

    //=================================================
    //  C a l l b a c k   a n d   T i m e r
    //=================================================
    virtual void timeTriggered() = 0;

    rclcpp::TimerBase::SharedPtr periodTimer_;

    void timeTriggeredCaller();

    // Used for thread locking
    std::mutex mutex_;

    // Used by receiveInputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*>> inDataPortTupleVector;
    // Used by receiveInputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*>> inEventPortTupleVector;
    // Used by sendOutputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (tcp_opInterface_base::*)(MsgType)>> outPortTupleVector;
};
