#include "rclcpp/rclcpp.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/temperature.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/empty.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/fan_ack.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/set_point.hpp"
#include "temp_control_mixed_u_ros_cpp_pkg_interfaces/msg/fan_cmd.hpp"
#include <queue>
#include <vector>
#include <variant>
#include <mutex>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

class tcp_tempControl_base : public rclcpp::Node
{
protected:
    using MsgType = std::variant<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature, temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Empty, temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck, temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint, temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd>;

    tcp_tempControl_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================

    #define MESSAGE_TO_STRING(message) temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::to_yaml(message).c_str()
    #define PRINT_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define PRINT_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define PRINT_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)

    void put_fanCmd(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd msg);

    temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature get_currentTemp();

    // Methods to be used to set initial values for data ports
    void init_currentTemp(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature val);

private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    void accept_currentTemp(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature msg);
    void accept_tempChanged(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Empty msg);
    void accept_fanAck(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck msg);
    void accept_setPoint(temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint msg);

    // Methods for working with port queues
    void receiveInputs(std::queue<MsgType>& infrastructureQueue, std::queue<MsgType>& applicationQueue);

    void sendOutputs();

    void enqueue(std::queue<MsgType>& queue, MsgType val);

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;

    void dataSubscriptionHandler(MsgType msg, std::queue<MsgType>& queue);

    void eventSubscriptionHandler(MsgType msg, std::queue<MsgType>& infrastructureQueue, std::queue<MsgType>& applicationQueue, void (tcp_tempControl_base::*handleMsg)(MsgType));


    //=================================================
    //  C o m p u t e    E n t r y    P o i n t
    //=================================================
    virtual void handle_tempChanged() = 0;
    void handle_tempChanged_base(MsgType msg);
    virtual void handle_fanAck(const temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck msg) = 0;
    void handle_fanAck_base(MsgType msg);
    virtual void handle_setPoint(const temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint msg) = 0;
    void handle_setPoint_base(MsgType msg);

    std::queue<MsgType> infrastructureIn_currentTemp;
    std::queue<MsgType> applicationIn_currentTemp;
    std::queue<MsgType> infrastructureIn_tempChanged;
    std::queue<MsgType> applicationIn_tempChanged;
    std::queue<MsgType> infrastructureIn_fanAck;
    std::queue<MsgType> applicationIn_fanAck;
    std::queue<MsgType> infrastructureIn_setPoint;
    std::queue<MsgType> applicationIn_setPoint;

    std::queue<MsgType> infrastructureOut_fanCmd;
    std::queue<MsgType> applicationOut_fanCmd;

    void sendOut_fanCmd(MsgType msg);

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Temperature>::SharedPtr tcp_tempControl_currentTemp_subscription_;
    rclcpp::Subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::Empty>::SharedPtr tcp_tempControl_tempChanged_subscription_;
    rclcpp::Subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanAck>::SharedPtr tcp_tempControl_fanAck_subscription_;
    rclcpp::Subscription<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::SetPoint>::SharedPtr tcp_tempControl_setPoint_subscription_;

    rclcpp::Publisher<temp_control_mixed_u_ros_cpp_pkg_interfaces::msg::FanCmd>::SharedPtr tcp_tempControl_fanCmd_publisher_;

    // Used for thread locking
    std::mutex mutex_;

    // Used by receiveInputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*>> inDataPortTupleVector;
    // Used by sendOutputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (tcp_tempControl_base::*)(MsgType)>> outPortTupleVector;
};
