#include "uros_demo_naming_cpp_pkg/user_headers/proc_joy_src.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

proc_joy::proc_joy() : proc_joy_base()
{
    // Invoke initialize entry point
    initialize();

    PRINT_INFO("proc_joy infrastructure set up");
}

int main(int argc, char **argv)
{
    rclcpp::init(argc, argv);
    auto executor = rclcpp::executors::MultiThreadedExecutor();
    auto node = std::make_shared<proc_joy>();
    executor.add_node(node);
    executor.spin();
    rclcpp::shutdown();
    return 0;
}
