#ifndef EXAMPLE_TYPES_HPP
#define EXAMPLE_TYPES_HPP

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include "datatypes_system_cpp_pkg_interfaces/msg/my_struct2i.hpp"
#include "datatypes_system_cpp_pkg_interfaces/msg/my_structi.hpp"

static inline datatypes_system_cpp_pkg_interfaces::msg::MyStruct2i example_MyStruct2i();
static inline datatypes_system_cpp_pkg_interfaces::msg::MyStructi example_MyStructi();

static inline datatypes_system_cpp_pkg_interfaces::msg::MyStruct2i example_MyStruct2i() {
    datatypes_system_cpp_pkg_interfaces::msg::MyStruct2i msg;
    msg.field_float.data = 0.0;
    msg.field_s_char.data = 0;
    return msg;
}

static inline datatypes_system_cpp_pkg_interfaces::msg::MyStructi example_MyStructi() {
    datatypes_system_cpp_pkg_interfaces::msg::MyStructi msg;
    msg.field_int64.data = 0;
    msg.field_str.data = "";
    msg.field_enum.my_enum = datatypes_system_cpp_pkg_interfaces::msg::MyEnum::MY_ENUM_ON;
    msg.field_rec = example_MyStruct2i();
    return msg;
}

#endif  // EXAMPLE_TYPES_HPP
