// #Sireum

package bc.BuildingControl

import org.sireum._
import bc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Temperature_impl {
  def example(): BuildingControl.Temperature_impl = {
    return BuildingControl.Temperature_impl(
      degrees = Base_Types.Float_32_example(),
      unit = BuildingControl.TempUnit.byOrdinal(0).get)
  }
}

@datatype class Temperature_impl(
  val degrees: F32,
  val unit: BuildingControl.TempUnit.Type) {
}

object Temperature_impl_Payload {
  def example(): Temperature_impl_Payload = {
    return Temperature_impl_Payload(BuildingControl.Temperature_impl.example())
  }
}

@datatype class Temperature_impl_Payload(value: BuildingControl.Temperature_impl) extends art.DataContent
