#include "rclcpp/rclcpp.hpp"
#include "fan_in_fan_out_system_cpp_pkg_interfaces/msg/integer64.hpp"
#include <queue>
#include <sstream>
#include <vector>
#include <variant>
#include <mutex>
#include <utility>

#include "fan_in_fan_out_system_cpp_pkg/base_headers/example_types.hpp"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

static inline std::string _messageToString(const fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64& msg) {
    std::ostringstream oss;
    oss << msg.data;
    return oss.str();
}

class fanOut_consumer1_base : public rclcpp::Node
{
protected:
    using MsgType = std::variant<fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64>;

    fanOut_consumer1_base();

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================

    #define MESSAGE_TO_STRING(message) _messageToString(message).c_str()
    #define LOG_INFO(...) RCLCPP_INFO(this->get_logger(), __VA_ARGS__)
    #define LOG_WARN(...) RCLCPP_WARN(this->get_logger(), __VA_ARGS__)
    #define LOG_ERROR(...) RCLCPP_ERROR(this->get_logger(), __VA_ARGS__)


private:
    rclcpp::CallbackGroup::SharedPtr cb_group_;

    void accept_myInteger(fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64 msg);

    // Methods for working with port queues
    void receiveInputs(std::queue<MsgType>& infrastructureQueue, std::queue<MsgType>& applicationQueue);

    void sendOutputs();

    void enqueue(std::queue<MsgType>& queue, MsgType val);

    // SubscriptionOptions for assigning subscriptions to the callback group
    rclcpp::SubscriptionOptions subscription_options_;

    void dataSubscriptionHandler(MsgType msg, std::queue<MsgType>& queue);

    void eventSubscriptionHandler(MsgType msg, std::queue<MsgType>& infrastructureQueue, std::queue<MsgType>& applicationQueue, void (fanOut_consumer1_base::*handleMsg)(MsgType));


    //=================================================
    //  C o m p u t e    E n t r y    P o i n t
    //=================================================
    virtual void handle_myInteger(const fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64 msg) = 0;
    void handle_myInteger_base(MsgType msg);

    std::queue<MsgType> infrastructureIn_myInteger;
    std::queue<MsgType> applicationIn_myInteger;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rclcpp::Subscription<fan_in_fan_out_system_cpp_pkg_interfaces::msg::Integer64>::SharedPtr fanOut_consumer1_myInteger_subscription_;


    // Used for thread locking
    // Guards the port queues.  Never held across the compute entry point -- user code
    // calls put_<port>/get_<port>, which take it themselves.
    std::mutex state_mutex_;

    // Held for the length of a dispatch so dispatches do not overlap.  The callback
    // group is Reentrant, so without this two arrivals on the same port could run the
    // entry point concurrently.
    std::mutex dispatch_mutex_;

    // Used by receiveInputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*>> inDataPortTupleVector;
    // Used by sendOutputs
    std::vector<std::tuple<std::queue<MsgType>*, std::queue<MsgType>*, void (fanOut_consumer1_base::*)(MsgType)>> outPortTupleVector;
};
