#ifndef PROC_TTJ_BASE_H
#define PROC_TTJ_BASE_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <stdio.h>
#include <rcl/rcl.h>
#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <rcutils/logging_macros.h>
#include "sensor_msgs/msg/joy.h"
#include "geometry_msgs/msg/twist.h"

#include "uros_demo_gumbo_microros_pkg/base_headers/example_types.h"

// Logger name used by the PRINT_* macros.  It defaults to the node name and is
// updated to the node's actual logger name (rcl_node_get_logger_name) during
// proc_ttj_base_init.
extern const char * proc_ttj_logger_name;

#define PRINT_INFO(fmt, ...) RCUTILS_LOG_INFO_NAMED(proc_ttj_logger_name, fmt, ##__VA_ARGS__)
#define PRINT_WARN(fmt, ...) RCUTILS_LOG_WARN_NAMED(proc_ttj_logger_name, fmt, ##__VA_ARGS__)
#define PRINT_ERROR(fmt, ...) RCUTILS_LOG_ERROR_NAMED(proc_ttj_logger_name, fmt, ##__VA_ARGS__)


//=================================================
//  N o d e   S t a t e
//=================================================

typedef struct {
    rcl_node_t node;
    rclc_support_t support;
    rcl_allocator_t allocator;

    //=================================================
    //  C o m m u n i c a t i o n
    //=================================================
    rcl_publisher_t proc_ttj_cmdVel_publisher;

    //=================================================
    //  S u b s c r i p t i o n s
    //=================================================
    rcl_subscription_t proc_ttj_joy_subscription;
    sensor_msgs__msg__Joy proc_ttj_joy_msg;

    //=================================================
    //  E x e c u t o r
    //=================================================
    rclc_executor_t executor;
} proc_ttj_base_t;

void proc_ttj_base_init(proc_ttj_base_t * self);
void proc_ttj_base_spin(proc_ttj_base_t * self);

//=================================================
//  C o m m u n i c a t i o n
//=================================================

void put_cmdVel(proc_ttj_base_t * self, geometry_msgs__msg__Twist * msg);

#endif  // PROC_TTJ_BASE_H
