// #Sireum

package prod_cons__JVM.ProdConsFlows

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import prod_cons__JVM.GumboXUtil.GumboXResult
import prod_cons__JVM.util.{Container, Profile, UnitTestConfigurationBatch}
import prod_cons__JVM.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object Consumer_p_consumer_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultComputeProfile = Consumer_p_consumer_Profile_P

  def defaultComputeConfig: Consumer_p_consumer_Compute_UnitTestConfiguration = {
    return (Consumer_p_consumer_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Consumer_p_consumer_Profile_P (
        name = "Compute_Default_Profile",
        api_h_event_in = freshRandomLib,
        api_f_event_data_in = freshRandomLib,
        api_g_event_data_in = freshRandomLib,
        api_e_data_in = freshRandomLib
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = prod_cons__JVM.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${prod_cons__JVM.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = prod_cons__JVM.JSON.toProdConsFlowsConsumer_p_consumer_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class Consumer_p_consumer_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Consumer_p_consumer_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Consumer_p_consumer_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[Consumer_p_consumer_PreState_Container])
  }
}
