// #Sireum

package prod_cons__JVM.ProdConsFlows

import org.sireum._
import prod_cons__JVM.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile with generators for incoming ports
@record class Producer_p_producer_Profile_P(
  val name: String,
  val numTests: Z, // number of tests to generate
  )

// Profile with generators for state variables and incoming ports
@record class Producer_p_producer_Profile_PS(
  val name: String,
  val numTests: Z, // number of tests to generate
  )
