// #Sireum

package prod_cons__JVM.ProdConsFlows

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import prod_cons__JVM.GumboXUtil.GumboXResult
import prod_cons__JVM.util.{Container, Profile, UnitTestConfigurationBatch}
import prod_cons__JVM.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object Producer_p_producer_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  val tq: String = "\"\"\""

  type DefaultInitializeProfile = Producer_p_producer_Profile

  def defaultInitializeConfig: Producer_p_producer_Initialize_UnitTestConfiguration = {
    return (Producer_p_producer_Initialize_UnitTestConfiguration (
      verbose = F,
      name = "Default_Initialize_Config",
      description = "Default Initialize Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Producer_p_producer_Profile (
        name = "Initialize_Default_Profile",
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => None())
    )
  }

  type DefaultComputeProfile = Producer_p_producer_Profile_P

  def defaultComputeConfig: Producer_p_producer_Compute_UnitTestConfiguration = {
    return (Producer_p_producer_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = Producer_p_producer_Profile_P (
        name = "Compute_Default_Profile",
      ),
      genReplay = (c: Container, testName: String, r: GumboXResult.Type) => Some(
       st"""Replay Unit Test:
            |  test("Replay: $testName") {
            |    val results = prod_cons__JVM.GumboXUtil.GumboXResult.$r
            |    val json = st${tq}${prod_cons__JVM.JSON.fromutilContainer(c, T)}${tq}.render
            |    val testVector = prod_cons__JVM.JSON.toProdConsFlowsProducer_p_producer_PreState_Container_P(json).left
            |    assert (testComputeCBV(testVector) == results)
            |  }""".render))
    )
  }
}

@record class Producer_p_producer_Initialize_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Producer_p_producer_Profile_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Producer_p_producer_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testInitialiseCB()
  }
}

@record class Producer_p_producer_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Producer_p_producer_Profile_P_Trait,
  var genReplay: (Container, String, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with Producer_p_producer_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[Producer_p_producer_PreState_Container_P])
  }
}
