// #Sireum

package prod_cons__JVM.ProdConsFlows

import org.sireum._
import prod_cons__JVM.util.Profile
import prod_cons__JVM.util.EmptyContainer
import prod_cons__JVM.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@msig trait Producer_p_producer_Profile_Trait extends Profile

@record class Producer_p_producer_Profile (
  val name: String,
) extends Producer_p_producer_Profile_Trait {

  override def next: EmptyContainer = {
    return EmptyContainer()
  }
}

// Profile with generators for incoming ports
@msig trait Producer_p_producer_Profile_P_Trait extends Profile {
}

@record class Producer_p_producer_Profile_P(
  val name: String,
  ) extends Producer_p_producer_Profile_P_Trait {

  override def next: Producer_p_producer_PreState_Container_P = {
    return (Producer_p_producer_PreState_Container_P (
      ))
  }
}

// Profile with generators for state variables and incoming ports
@msig trait Producer_p_producer_Profile_PS_Trait extends Profile {
}

@record class Producer_p_producer_Profile_PS(
  val name: String,
  ) extends Producer_p_producer_Profile_PS_Trait {

  override def next: Producer_p_producer_PreState_Container_PS = {
    return (Producer_p_producer_PreState_Container_PS (
      ))
  }
}
