package org.sireum.hamr.codegen.test.microkit

// Regression tests for the Microkit reporter's C bridge parser. A data port whose
// payload is Base_Types::Boolean yields a global 'bool last_<port>_payload;' after the
// '#define's; the parser used to treat every 'bool' there as a method and reject the ';'.

import org.sireum._
import org.sireum.hamr.codegen.microkit.plugins.reporting.CContainers.{CField, CMethod}
import org.sireum.hamr.codegen.microkit.plugins.reporting.{CParser, Parsers}
import org.sireum.message.Reporter
import org.sireum.test.TestSuite

class CParserTest extends TestSuite {

  // generated consumer bridge for a Base_Types::Boolean data port
  val boolDataPortBridge: Predef.String =
    """#include "consumer_p_p_consumer.h"
      |
      |// Do not edit this file as it will be overwritten if HAMR codegen is rerun
      |
      |void consumer_p_p_consumer_initialize(void);
      |void consumer_p_p_consumer_notify(microkit_channel channel);
      |void consumer_p_p_consumer_timeTriggered(void);
      |
      |volatile sb_queue_bool_1_t *read_port_queue_1;
      |sb_queue_bool_1_Recv_t read_port_recv_queue;
      |
      |#define PORT_FROM_MON 0
      |
      |bool last_read_port_payload;
      |
      |bool get_read_port(bool *data) {
      |  sb_event_counter_t numDropped;
      |  bool fresh_data;
      |  bool isFresh = sb_queue_bool_1_dequeue((sb_queue_bool_1_Recv_t *) &read_port_recv_queue, &numDropped, &fresh_data);
      |  if (isFresh) {
      |    last_read_port_payload = fresh_data;
      |  }
      |  *data = last_read_port_payload;
      |  return isFresh;
      |}
      |
      |void init(void) {
      |  printf("%s | INIT!\n", microkit_name);
      |
      |  sb_queue_bool_1_Recv_init(&read_port_recv_queue, (sb_queue_bool_1_t *) read_port_queue_1);
      |
      |  consumer_p_p_consumer_initialize();
      |
      |  microkit_notify(PORT_FROM_MON);
      |}
      |
      |void notified(microkit_channel channel) {
      |  switch (channel) {
      |    case PORT_FROM_MON:
      |      consumer_p_p_consumer_timeTriggered();
      |      break;
      |    default:
      |      consumer_p_p_consumer_notify(channel);
      |  }
      |}
      |""".stripMargin

  val tests = Tests {

    * - {
      val root = Os.tempDir()
      val f = root / "consumer_p_p_consumer.c"
      f.writeOver(boolDataPortBridge)

      val reporter = Reporter.create
      val cFile = CParser.parse(f, root, reporter)
      root.removeAll()

      reporter.printMessages()
      assert(!reporter.hasError)

      val methods = cFile.items.filter(_.isInstanceOf[CMethod]).map(_.asInstanceOf[CMethod].identifier)
      assert(methods == ISZ[String]("get_read_port", "init", "notified"))

      val last = cFile.getField("last_read_port_payload")
      assert(last.typ == String("bool") && !last.isVolatile)

      // the reporter's lookups for the port still resolve
      assert(cFile.getMethgod("get_read_port").identifier == String("get_read_port"))
      assert(cFile.getField("read_port_queue_1").isVolatile)
    }

    * - {
      // a parse failure is reported as a warning, not an error, so it can't fail codegen
      val root = Os.tempDir()
      val f = root / "bad.c"
      f.writeOver(
        """#define PORT_FROM_MON 0
          |
          |void not_a_method;
          |""".stripMargin)

      val reporter = Reporter.create
      val cFileOpt = Parsers.parseC(f, root, reporter)
      root.removeAll()

      reporter.printMessages()
      assert(cFileOpt.isEmpty)
      assert(!reporter.hasError)
      assert(reporter.warnings.size == 1 && reporter.warnings(0).kind == String("CParser"))
    }
  }
}
