#include "temp_control_mixed_u_ros_microros_pkg/user_headers/tcp_tempSensor_src.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

static tcp_tempSensor_base_t node;

int main(int argc, char ** argv)
{
    (void)argc;
    (void)argv;

    tcp_tempSensor_base_init(&node);

    // Invoke initialize entry point
    tcp_tempSensor_initialize(&node);

    PRINT_INFO("tcp_tempSensor infrastructure set up");

    tcp_tempSensor_base_spin(&node);

    return 0;
}
