#include "temp_control_mixed_u_ros_microros_pkg/user_headers/tcp_tempControl_src.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
// To prevent overwriting, add '//@  hamr:no-overwrite' to this file

static tcp_tempControl_base_t node;

int main(int argc, char ** argv)
{
    (void)argc;
    (void)argv;

    tcp_tempControl_base_init(&node);

    // Invoke initialize entry point
    tcp_tempControl_initialize(&node);

    PRINT_INFO("tcp_tempControl infrastructure set up");

    tcp_tempControl_base_spin(&node);

    return 0;
}
