#ifndef PROC_ENCODER_SRC_H
#define PROC_ENCODER_SRC_H

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include "turtle_control_structure_microros_pkg/base_headers/proc_encoder_base_src.h"

//=================================================
//  I n i t i a l i z e    E n t r y    P o i n t
//=================================================
void proc_encoder_initialize(proc_encoder_base_t * self);

//=================================================
//  C o m p u t e    E n t r y    P o i n t
//=================================================
void proc_encoder_timeTriggered(proc_encoder_base_t * self);

#endif  // PROC_ENCODER_SRC_H
