// #Sireum

package isolette.Monitor

import org.sireum._
import art._
import isolette.SystemTestSuiteSlang.runtimeMonitorStream
import isolette._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_SystemTestAPI {
  /** helper method to set the values of all incoming ports
    * @param api_current_tempWstatus incoming data port
    * @param api_interface_failure incoming data port
    * @param api_internal_failure incoming data port
    */
  def put_concrete_inputs(api_current_tempWstatus: Isolette_Data_Model.TempWstatus_impl,
                          api_interface_failure: Isolette_Data_Model.Failure_Flag_impl,
                          api_internal_failure: Isolette_Data_Model.Failure_Flag_impl): Unit = {
    put_current_tempWstatus(api_current_tempWstatus)
    put_interface_failure(api_interface_failure)
    put_internal_failure(api_internal_failure)
  }

  // setter for incoming data port
  def put_current_tempWstatus(value: Isolette_Data_Model.TempWstatus_impl): Unit = {
    Art.insertInInfrastructurePort(Arch.isolette_single_sensor_Instance_thermostat_monitor_temperature_manage_monitor_mode.operational_api.current_tempWstatus_Id, Isolette_Data_Model.TempWstatus_impl_Payload(value))
  }

  // setter for incoming data port
  def put_interface_failure(value: Isolette_Data_Model.Failure_Flag_impl): Unit = {
    Art.insertInInfrastructurePort(Arch.isolette_single_sensor_Instance_thermostat_monitor_temperature_manage_monitor_mode.operational_api.interface_failure_Id, Isolette_Data_Model.Failure_Flag_impl_Payload(value))
  }

  // setter for incoming data port
  def put_internal_failure(value: Isolette_Data_Model.Failure_Flag_impl): Unit = {
    Art.insertInInfrastructurePort(Arch.isolette_single_sensor_Instance_thermostat_monitor_temperature_manage_monitor_mode.operational_api.internal_failure_Id, Isolette_Data_Model.Failure_Flag_impl_Payload(value))
  }

  def fetchContainer(): isolette.Monitor.Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_PostState_Container_PS = {
    if (runtimeMonitorStream.contains(Arch.isolette_single_sensor_Instance_thermostat_monitor_temperature_manage_monitor_mode.id)) {
      val (_, postContainer_) = runtimeMonitorStream.get(Arch.isolette_single_sensor_Instance_thermostat_monitor_temperature_manage_monitor_mode.id).get
      return postContainer_.asInstanceOf[isolette.Monitor.Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_PostState_Container_PS]
    }
    else {
      assert(F, s"No post state recorded for ${Arch.isolette_single_sensor_Instance_thermostat_monitor_temperature_manage_monitor_mode.name}")
      halt(s"No post state recorded for ${Arch.isolette_single_sensor_Instance_thermostat_monitor_temperature_manage_monitor_mode.name}")
    }
  }

  def check_concrete_outputs(api_monitor_mode: Isolette_Data_Model.Monitor_Mode.Type): Unit = {
    var failureReasons: ISZ[ST] = ISZ()

    val actual_monitor_mode = get_api_monitor_mode()
    if (api_monitor_mode != actual_monitor_mode) {
      failureReasons = failureReasons :+ st"'monitor_mode' did not match expected.  Expected: $api_monitor_mode, Actual: $actual_monitor_mode"
    }

    assert(failureReasons.isEmpty, st"${(failureReasons, "\n")}".render)
  }

  def get_api_monitor_mode(): Isolette_Data_Model.Monitor_Mode.Type = {
    return fetchContainer().api_monitor_mode
  }
}