#include "uros_demo_structure_microros_pkg/user_headers/proc_ttj_src.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

static proc_ttj_base_t node;

int main(int argc, char ** argv)
{
    (void)argc;
    (void)argv;

    proc_ttj_base_init(&node);

    // Invoke initialize entry point
    proc_ttj_initialize(&node);

    PRINT_INFO("proc_ttj infrastructure set up");

    proc_ttj_base_spin(&node);

    return 0;
}
