// #Sireum

package tc.TempSensor

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

import org.sireum._
import tc.GumboXUtil.GumboXResult
import tc.util.{Container, Profile, UnitTestConfigurationBatch}
import tc.RandomLib
import org.sireum.Random.Impl.Xoshiro256

object TempSensor_s_tcproc_tempSensor_UnitTestConfiguration_Util {

  def freshRandomLib: RandomLib = {
    return RandomLib(Random.Gen64Impl(Xoshiro256.create))
  }

  def defaultInitializeConfig: TempSensor_s_tcproc_tempSensor_Initialize_UnitTestConfiguration = {
    return (TempSensor_s_tcproc_tempSensor_Initialize_UnitTestConfiguration (
      verbose = F,
      name = "Default_Initialize_Config",
      description = "Default Initialize Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = TempSensor_s_tcproc_tempSensor_Profile (
        name = "Initialize_Default_Profile", // needed for old framework
        numTests = 100, // needed for old framework
      ),
      genReplay = (c: Container, r: GumboXResult.Type) => None())
    )
  }

  def defaultComputeConfig: TempSensor_s_tcproc_tempSensor_Compute_UnitTestConfiguration = {
    return (TempSensor_s_tcproc_tempSensor_Compute_UnitTestConfiguration (
      verbose = F,
      name = "Default_Compute_Config",
      description = "Default Compute Configuration",
      numTests = 100,
      numTestVectorGenRetries = 100,
      failOnUnsatPreconditions = F,
      profile = TempSensor_s_tcproc_tempSensor_Profile_P (
        name = "Compute_Default_Profile", // needed for old framework
        numTests = 100, // needed for old framework
        numTestVectorGenRetries = 100, // needed for old framework
      ),
      genReplay = (c: Container, r: GumboXResult.Type) => Some(
        st"""val testVector = tc.JSON.toTempSensorTempSensor_s_tcproc_tempSensor_PreState_Container_P(json).left
            |assert (testComputeCBV(testVector) == results)""".render))
    )
  }
}

@record class TempSensor_s_tcproc_tempSensor_Initialize_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Profile,
  var genReplay: (Container, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with TempSensor_s_tcproc_tempSensor_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testInitialiseCB()
  }
}

@record class TempSensor_s_tcproc_tempSensor_Compute_UnitTestConfiguration (
  var verbose: B,
  var name: String,
  var description: String,
  var numTests: Z,
  var numTestVectorGenRetries: Z,
  var failOnUnsatPreconditions: B,
  var profile: Profile,
  var genReplay: (Container, GumboXResult.Type) => Option[String])
  extends UnitTestConfigurationBatch with TempSensor_s_tcproc_tempSensor_GumboX_TestHarness {

  override def test(c: Container): GumboXResult.Type = {
    return testComputeCBV(c.asInstanceOf[TempSensor_s_tcproc_tempSensor_PreState_Container_P])
  }
}
