// #Sireum

package prod_cons__JVM.ProdConsFlows

import org.sireum._
import prod_cons__JVM._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Container_i {
  def example(): ProdConsFlows.Container_i = {
    return ProdConsFlows.Container_i(
      value = Base_Types.Integer_example())
  }
}

@datatype class Container_i(
  val value: Z) {
  @spec def gtZero = Invariant(
    value > 0
  )
}

object Container_i_Payload {
  def example(): Container_i_Payload = {
    return Container_i_Payload(ProdConsFlows.Container_i.example())
  }
}

@datatype class Container_i_Payload(value: ProdConsFlows.Container_i) extends art.DataContent
