// #Sireum

package prod_cons__JVM.ProdConsFlows

import org.sireum._
import prod_cons__JVM._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
object Container_i_GumboX {
  /** invariant gtZero
    *   Must be greater than zero
    */
  @strictpure def gtZero_Invariant(value: ProdConsFlows.Container_i): B =
    value.value > 0

  /** D-Inv Data Invariant for ProdConsFlows.Container_i
    */
  @strictpure def D_Inv_Container_i(value: ProdConsFlows.Container_i): B =
    (gtZero_Invariant(value))

  /** D-Inv-Guard Data Invariant for ProdConsFlows.Container_i
    */
  @strictpure def D_Inv_Guard_Container_i(value: Option[ProdConsFlows.Container_i]): B =
    value.nonEmpty -->: D_Inv_Container_i(value.get)
}